ifdef::env-github[]
:note-caption: :information_source:
endif::[]

= OpenXR™ API Documentation Project

This repository contains sources for the formal documentation of the OpenXR
API. This includes:

[options="compact"]
 * the OpenXR API Specification
 * OpenXR header files (generated from the specification)
 * related tools and scripts.

The authoritative public repository is located at
https://github.com/KhronosGroup/OpenXR-Docs/.
It hosts public Issue tracker, and accepts patches (Pull Requests) from the
general public.

== Directory Structure

The directory structure is as follows:

```
README.adoc           This file
COPYING.md            Copyright and licensing information
CODE_OF_CONDUCT.md    Code of Conduct
specification/        Specification - files to generate the spec
include/openxr/       Static OpenXR header (not generated from the Registry)
```

== Building the Specification and Reference Pages, and Regenerating Headers

The document sources are marked up in Asciidoctor format, and we use
`asciidoctor` and related toolchain components to generate output documents.
See link:specification/README.md[specification/README.md]
for more information on installing the toolchain and building the
Specification.
