# Copyright (c) 2022-2024, The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gem 'asciidoctor', '~>2.0.10'
gem 'rouge'
gem 'asciidoctor-pdf', '1.6.2'

# Temporary fix
# https://stackoverflow.com/questions/71392585/asciidoctor-pdf-cannot-load-such-file-matrix-loaderror#comment132483860_71392586
gem "matrix", "~> 0.4"

gem 'hexapdf'
