#!/usr/bin/env bash
#
# Copyright 2016-2022 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

# makeKHRAndKHX - invoke Makefile with the right options to build with all
# KHR and KHX extensions included.
# NOTE: there are currently no KHX extensions. This just builds KHR
# extensions. Fixing this will require updates to scripts/extdependency.py
# and makeSpec.

# Usage: makeKHRAndKHX targets

set -e
(
    cd "$(dirname "$0")"
    ./makeSpec -spec khr $*
)
