#!/usr/bin/env bash
#
# Copyright 2016-2022 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

# makeKHR - invoke Makefile with the right options to build with all
# KHR extensions included.

# Usage: makeKHR targets

set -e
(
    cd "$(dirname "$0")"
    ./makeSpec -spec khr $*
)
