#!/usr/bin/env bash
#
# Copyright (c) 2016-2020 The Khronos Group Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Adapted from the Vulkan project for OpenXR.

# makeExt - invoke Makefile with the right options to build with a
# specific extension or extensions included. The extension currently
# must be a single argument, but that argument may contain a quoted,
# space-separated list of extension names.
#
# Dependencies on other extensions are automatically added. This
# script requires features introduced in bash 4.0.
#
# Usage: makeExt extension targets

set -e

(
    cd $(dirname $0)
    # Generate extension lists from xr.xml
    make out/extDependency.sh || exit

    # Load extension lists
    source out/extDependency.sh

    extension=$1
    shift
    echo extension is $extension targets are $*

    # Determine the set of required extensions based on requested extensions
    declare -A required

    # Allow multiple extension names in a single argument
    for name in $extension ; do
        # Add to the required list
        required[$name]=1
        # If it has dependencies, add all of them to the required list
        if [ ${extensions[$name]+_} ] ; then
            deps=${extensions[$name]}
            for dep in $deps ; do
                required[$dep]=1
            done
        fi
    done

    # Something weird in bash quoting requires this two-step process to define
    # EXTENSIONS to make.
    args="${!required[@]}"
    make EXTENSIONS="$args" APITITLE="(with extension $extension)" $*
)
