// Copyright (c) 2023-2026, Google LLC
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/XR_ANDROID_recommended_resolution.adoc[]

*IP Status*::
    No known IP claims.

*Contributors*::
    Trevor Debrechtabel, Google +
    Spencer Quin, Google +
    Lachlan Ford, Google +
    Vasiliy Baranov, Google +

==== Overview

This extension allows the runtime to notify the application when the
recommended resolution changes, based on current system performance, device
thermals, or other factors.

This extension modifies the specification in the following way:

* The runtime may: return non-identical buffer contents from the
  flink:xrEnumerateViewConfigurationViews enumeration for the given
  pname:systemId and pname:viewConfigurationType for the lifetime of the
  instance.

[open,refpage='XrEventDataRecommendedResolutionChangedANDROID',type='structs',desc='The runtime event that is sent when the recommended resolution changes.',xrefs='']
--
The slink:XrEventDataRecommendedResolutionChangedANDROID structure is
defined as:

include::{generated}/api/structs/XrEventDataRecommendedResolutionChangedANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
****

Receiving the slink:XrEventDataRecommendedResolutionChangedANDROID event
structure indicates that the recommended resolution has changed.
The application should: query the runtime for the new recommended resolution
using flink:xrEnumerateViewConfigurationViews.

include::{generated}/validity/structs/XrEventDataRecommendedResolutionChangedANDROID.adoc[]
--

==== Example code

The following example code demonstrates how to listen for recommended
resolution change events.

[source,cpp]
----
// Created at app startup time.
XrInstance instance;
XrSystemId systemId; // Previously initialized.
uint32_t viewCountOutput; // Previously initialized.

// View configuration type the application uses.
XrViewConfigurationType viewConfigType;

// Poll events for recommended resolution changes.
XrEventDataBuffer event = {XR_TYPE_EVENT_DATA_BUFFER};
XrResult result = xrPollEvent(instance, &event);
if (result == XR_SUCCESS) {
  switch (event.type) {
    case XR_TYPE_EVENT_DATA_RECOMMENDED_RESOLUTION_CHANGED_ANDROID: {
        uint32_t viewCapacityInput = viewCountOutput;
        std::vector<XrViewConfigurationView> views(viewCapacityInput);
        result = xrEnumerateViewConfigurationViews(instance, systemId,
          viewConfigType, viewCapacityInput, &viewCountOutput, views.data());
        if(!XR_SUCCEEDED(result)) {
          // Handle error
        }

        // New recommended resolution is found in
        // views.recommendedImageRectWidth and views.recommendedImageRectHeight
        // Change the resolution for the viewConfigType
      break;
    }
    default:
      break;
  }
}
----

==== Version History

* Revision 1, 2025-04-04 (Kenny Vercaemer)
** Initial extension description
