// Copyright (c) 2023-2026, Google LLC
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/XR_ANDROID_scene_meshing.adoc[]

*Last Modified Date*::
    2025-05-15

*IP Status*::
    No known IP claims.

*Contributors*::
    Spencer Quin, Google +
    Jared Finder, Google +
    Antonio Fontan, Google +
    Cairn Overturf, Google +
    Nihav Jain, Google +
    Salar Khan, Google +
    Sebastian Klose, Google +
    Jürgen Sturm, Google +
    Vinny DaSilva, Google +
    Ricardo Campbell, Google +

==== Overview

This extension is intended to provide meshes that approximately represent
the physical objects in the user's environment.

Applications can: use this extension to visualize the scene and to let
virtual objects interact with physical objects such as collisions.

The scene mesh data is generated by the runtime and shared with the
application using slink:XrSceneMeshingTrackerANDROID and
slink:XrSceneMeshSnapshotANDROID.
Applications can: access the values in scene submesh information through
slink:XrSceneSubmeshStateANDROID returned from
flink:xrGetAllSubmeshStatesANDROID.
Applications can: access the values in scene submesh data through
slink:XrSceneSubmeshDataANDROID returned from flink:xrGetSubmeshDataANDROID.

Scene meshing data is sensitive personal information and is closely linked
to personal privacy and integrity.
It is strongly recommended that applications that store or transfer scene
meshing data always ask the user for active and specific acceptance to do
so.

[IMPORTANT]
.Permissions
====
Android applications must: have the
android.permission.SCENE_UNDERSTANDING_FINE permission listed in their
manifest.
The android.permission.SCENE_UNDERSTANDING_FINE permission is considered a
sensitive permission as it allows the runtime to study the user environment.

The application must: request the permission at runtime to use these
functions:

* flink:xrCreateSceneMeshingTrackerANDROID
* flink:xrDestroySceneMeshingTrackerANDROID
* flink:xrCreateSceneMeshSnapshotANDROID
* flink:xrDestroySceneMeshSnapshotANDROID
* flink:xrGetAllSubmeshStatesANDROID
* flink:xrGetSubmeshDataANDROID

(protection level: dangerous)
====

==== Inspect system capability

[open,refpage='XrSystemSceneMeshingPropertiesANDROID',type='structs',desc='System property for scene meshing',xrefs='XrSystemProperties xrGetSystemProperties']
--
The slink:XrSystemSceneMeshingPropertiesANDROID structure is defined as:

include::{generated}/api/structs/XrSystemSceneMeshingPropertiesANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
* pname:supportsSceneMeshing is an basetype:XrBool32, indicating if the
  system supports scene meshing.
****

An application can: inspect whether the system is capable of scene meshing
by chaining an slink:XrSystemSceneMeshingPropertiesANDROID structure to the
slink:XrSystemProperties when calling flink:xrGetSystemProperties.

If a runtime returns ename:XR_FALSE for pname:supportsSceneMeshing, the
system does not support scene meshing, and therefore must: return
ename:XR_ERROR_FEATURE_UNSUPPORTED from
flink:xrCreateSceneMeshingTrackerANDROID.
The application should: avoid using scene meshing functionality when
pname:supportsSceneMeshing is ename:XR_FALSE.

If a runtime returns ename:XR_TRUE for pname:supportsSceneMeshing, the
system supports scene meshing.

include::{generated}/validity/structs/XrSystemSceneMeshingPropertiesANDROID.adoc[]
--

[open,refpage='XrSceneMeshSemanticLabelSetANDROID',type='enums',desc='Semantic label sets for scene meshing',xrefs='XrSceneMeshingTrackerCreateInfoANDROID XrSceneMeshSemanticLabelANDROID']
--
The elink:XrSceneMeshSemanticLabelSetANDROID enumeration describes the
semantic label sets for scene meshing.
Each value in this enum represents another enum that contains the semantic
labels.
For example, the ename:XR_SCENE_MESH_SEMANTIC_LABEL_SET_DEFAULT_ANDROID
value represents the set elink:XrSceneMeshSemanticLabelANDROID.

include::{generated}/api/enums/XrSceneMeshSemanticLabelSetANDROID.adoc[]

The enumeration values have the following meanings:

include::{generated}/api/enums/XrSceneMeshSemanticLabelSetANDROID.comments.adoc[]
--

[open,refpage='xrEnumerateSupportedSemanticLabelSetsANDROID',type='protos',desc='Gets the list of semantic label sets supported by the system',xrefs='XrSceneMeshSemanticLabelSetANDROID XrSceneMeshSemanticLabelANDROID']
--
The flink:xrEnumerateSupportedSemanticLabelSetsANDROID function is defined
as:

include::{generated}/api/protos/xrEnumerateSupportedSemanticLabelSetsANDROID.adoc[]

.Parameter Descriptions
****
* pname:instance is an slink:XrInstance created by the application.
* pname:systemId is an basetype:XrSystemId retried from flink:xrGetSystem.
* pname:supportedSemanticLabelSetsInputCapacity is the capacity of
  pname:supportedSemanticLabelSets, or 0 to retrieve the required capacity.
* pname:supportedSemanticLabelSetsOutputCount is a pointer to the count of
  pname:supportedSemanticLabelSets written, or a pointer to the required
  capacity in the case that pname:supportedSemanticLabelSetsInputCapacity is
  insufficient.
* pname:supportedSemanticLabelSets is a pointer to an array of
  elink:XrSceneMeshSemanticLabelSetANDROID.
  It can: be ename:NULL if pname:supportedSemanticLabelSetsInputCapacity is 0.
* See <<fundamentals-buffer-size-parameters, Buffer Size Parameters>>
  chapter for a detailed description of retrieving the required
  pname:supportedSemanticLabelSets size.
****

The application can: enumerate semantic label sets supported by the system
using flink:xrEnumerateSupportedSemanticLabelSetsANDROID function.

Every system must: at least support
ename:XR_SCENE_MESH_SEMANTIC_LABEL_SET_NONE_ANDROID because this enum value
represents no semantic label set and can: be used in the case the
application does not need vertex semantics.

include::{generated}/validity/protos/xrEnumerateSupportedSemanticLabelSetsANDROID.adoc[]
--

==== Create a scene meshing tracker handle

[open,refpage='XrSceneMeshingTrackerANDROID',type='handles',desc='Represents a scene meshing tracker']
--
include::{generated}/api/handles/XrSceneMeshingTrackerANDROID.adoc[]

The slink:XrSceneMeshingTrackerANDROID handle represents a scene meshing
tracker for scene meshing and managing the related resources.

This handle can: be used to create a scene mesh snapshot using
flink:xrCreateSceneMeshSnapshotANDROID in this extension.
--

[open,refpage='xrCreateSceneMeshingTrackerANDROID',type='protos',desc='Create a handle for scene mesh tracking',xrefs='XrSceneMeshingTrackerANDROID XrSceneMeshingTrackerCreateInfoANDROID xrDestroySceneMeshingTrackerANDROID']
--
The flink:xrCreateSceneMeshingTrackerANDROID function is defined as:

include::{generated}/api/protos/xrCreateSceneMeshingTrackerANDROID.adoc[]

.Parameter Descriptions
****
* pname:session is an slink:XrSession in which the scene meshing tracker
  will be active.
* pname:createInfo is a pointer to an
  slink:XrSceneMeshingTrackerCreateInfoANDROID structure used to describe
  the scene meshing tracker to be created.
* pname:tracker is the returned slink:XrSceneMeshingTrackerANDROID handle.
****

An application can: create an slink:XrSceneMeshingTrackerANDROID handle
using the flink:xrCreateSceneMeshingTrackerANDROID function.

If the system does not support scene meshing, the runtime must: return
ename:XR_ERROR_FEATURE_UNSUPPORTED from
flink:xrCreateSceneMeshingTrackerANDROID.
In this case, the runtime must: return ename:XR_FALSE for
slink:XrSystemSceneMeshingPropertiesANDROID::pname:supportsSceneMeshing when
the flink:xrGetSystemProperties function is called, so that the application
can: avoid creating a scene meshing tracker.

The application must: only use the semantic label sets that are supported by
the system in
slink:XrSceneMeshingTrackerCreateInfoANDROID::pname:semanticLabelSet when
creating a scene meshing tracker.
If the application uses an unsupported scene mesh vertex semantic label set,
the runtime must: return ename:XR_ERROR_FEATURE_UNSUPPORTED from
flink:xrCreateSceneMeshingTrackerANDROID.

The application can: enumerate the list of supported semantic label sets
with the flink:xrEnumerateSupportedSemanticLabelSetsANDROID function.

The flink:xrCreateSceneMeshingTrackerANDROID handle owns all the resources
for scene meshing.
Once finished with scene meshing experience, the application must: destroy
the handle via the flink:xrDestroySceneMeshingTrackerANDROID function.

include::{generated}/validity/protos/xrCreateSceneMeshingTrackerANDROID.adoc[]
--

[open,refpage='XrSceneMeshingTrackerCreateInfoANDROID',type='structs',desc='Information to create a scene meshing tracker handle',xrefs='xrCreateSceneMeshingTrackerANDROID XrSceneMeshingTrackerANDROID']
--
The slink:XrSceneMeshingTrackerCreateInfoANDROID structure is defined as:

include::{generated}/api/structs/XrSceneMeshingTrackerCreateInfoANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
* pname:semanticLabelSet is an elink:XrSceneMeshSemanticLabelSetANDROID used
  to specify the semantic label set to be used for the scene meshing.
  If this is set to ename:XR_SCENE_MESH_SEMANTIC_LABEL_SET_NONE_ANDROID, the
  runtime will ignore the
  slink:XrSceneSubmeshDataANDROID::pname:vertexSemantics buffer field.
* pname:enableNormals is an basetype:XrBool32 used to specify whether to
  include vertex normals for the mesh vertices in the scene mesh buffer when
  getting the scene mesh data.
****

The slink:XrSceneMeshingTrackerCreateInfoANDROID structure describes the
information to create an slink:XrSceneMeshingTrackerANDROID handle.

include::{generated}/validity/structs/XrSceneMeshingTrackerCreateInfoANDROID.adoc[]
--

[open,refpage='xrDestroySceneMeshingTrackerANDROID',type='protos',desc='Destroy a scene meshing tracker handle',xrefs='xrCreateSceneMeshingTrackerANDROID XrSceneMeshingTrackerANDROID']
--
The flink:xrDestroySceneMeshingTrackerANDROID function is defined as:

include::{generated}/api/protos/xrDestroySceneMeshingTrackerANDROID.adoc[]

.Parameter Descriptions
****
* pname:tracker is an slink:XrSceneMeshingTrackerANDROID previously created
  by flink:xrCreateSceneMeshingTrackerANDROID.
****

The flink:xrDestroySceneMeshingTrackerANDROID function releases the
pname:tracker and the underlying resources when finished with scene meshing
experiences.

include::{generated}/validity/protos/xrDestroySceneMeshingTrackerANDROID.adoc[]
--

==== Create a scene mesh snapshot handle

[open,refpage='XrSceneMeshSnapshotANDROID',type='handles',desc='Represents a scene mesh snapshot']
--
include::{generated}/api/handles/XrSceneMeshSnapshotANDROID.adoc[]

The slink:XrSceneMeshSnapshotANDROID handle represents a scene mesh
snapshot.
This snapshot is created by using flink:xrCreateSceneMeshSnapshotANDROID
which takes a snapshot of the scene mesh data at the time of the function
call.

This handle can: be used to retrieve submesh information and data using
flink:xrGetAllSubmeshStatesANDROID and flink:xrGetSubmeshDataANDROID.
--

[open,refpage='xrCreateSceneMeshSnapshotANDROID',type='protos',desc='Creates a scene mesh snapshot',xrefs='XrSceneMeshingTrackerANDROID XrSceneMeshSnapshotCreateInfoANDROID XrSceneMeshSnapshotCreationResultANDROID XrSceneMeshSnapshotANDROID']
--
The flink:xrCreateSceneMeshSnapshotANDROID function is defined as:

include::{generated}/api/protos/xrCreateSceneMeshSnapshotANDROID.adoc[]

.Parameter Descriptions
****
* pname:tracker is an slink:XrSceneMeshingTrackerANDROID handle previously
  created with flink:xrCreateSceneMeshingTrackerANDROID.
* pname:createInfo is pointer to an
  slink:XrSceneMeshSnapshotCreateInfoANDROID structure which contains
  necessary information required to create the scene mesh snapshot.
* pname:outSnapshotCreationResult is a pointer to an
  slink:XrSceneMeshSnapshotCreationResultANDROID object which is populated
  by the runtime with the snapshot creation result.
****

The application can: use the flink:xrCreateSceneMeshSnapshotANDROID function
to create a scene mesh snapshot from the scene meshing tracker.
This function returns an slink:XrSceneMeshSnapshotANDROID handle along with
elink:XrSceneMeshTrackingStateANDROID wrapped in an
slink:XrSceneMeshSnapshotCreationResultANDROID structure.
The handle is technically a snapshot of the scene mesh data at the time of
creation.
This handle can: be used to query the scene mesh info and data using
flink:xrGetAllSubmeshStatesANDROID and flink:xrGetSubmeshDataANDROID
respectively.

include::{generated}/validity/protos/xrCreateSceneMeshSnapshotANDROID.adoc[]
--

[open,refpage='XrSceneMeshSnapshotCreateInfoANDROID',type='structs',desc='Information to create a scene mesh snapshot',xrefs='xrCreateSceneMeshSnapshotANDROID']
--
The slink:XrSceneMeshSnapshotCreateInfoANDROID structure is defined as:

include::{generated}/api/structs/XrSceneMeshSnapshotCreateInfoANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
* pname:baseSpace is an slink:XrSpace within which the scene submesh pose
  info is represented.
* pname:time is the basetype:XrTime that describes the time when the scene
  mesh will be processed or displayed, typically
  slink:XrFrameState::pname:predictedDisplayTime.
* pname:boundingBox is an slink:XrBoxf describing the bounding box within
  which to acquire the scene mesh.
****

The slink:XrSceneMeshSnapshotCreateInfoANDROID structure describes the
information to create an slink:XrSceneMeshSnapshotANDROID handle

include::{generated}/validity/structs/XrSceneMeshSnapshotCreateInfoANDROID.adoc[]
--

[open,refpage='XrSceneMeshSnapshotCreationResultANDROID',type='structs',desc='Stores the result of a scene mesh snapshot creation',xrefs='xrCreateSceneMeshSnapshotANDROID']
--
The slink:XrSceneMeshSnapshotCreationResultANDROID structure is defined as:

include::{generated}/api/structs/XrSceneMeshSnapshotCreationResultANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
* pname:snapshot is an slink:XrSceneMeshSnapshotANDROID handle created by
  the runtime.
* pname:trackingState is an elink:XrSceneMeshTrackingStateANDROID that
  describes the state of the scene meshing tracker at the time of the
  snapshot creation.
****

The slink:XrSceneMeshSnapshotCreationResultANDROID structure stores the
result of a scene mesh snapshot creation returned from
flink:xrCreateSceneMeshSnapshotANDROID.

include::{generated}/validity/structs/XrSceneMeshSnapshotCreationResultANDROID.adoc[]
--

[open,refpage='XrSceneMeshTrackingStateANDROID',type='enums',desc='Enum to describe the state of the scene meshing tracker',xrefs='XrSceneMeshSnapshotCreationResultANDROID']
--
The elink:XrSceneMeshTrackingStateANDROID enumeration describes the tracking
state for a scene meshing tracker.
Each value in this enum represents a state of the scene meshing tracker.

include::{generated}/api/enums/XrSceneMeshTrackingStateANDROID.adoc[]

The enumeration values have the following meanings:

include::{generated}/api/enums/XrSceneMeshTrackingStateANDROID.comments.adoc[]

This state serves only as additional information to the application.
In the absence of other sources of errors, the runtime must: continue to
allow the application to create snapshots and retrieve data from them
regardless of the current elink:XrSceneMeshTrackingStateANDROID of the
tracker.
If the state is not ename:XR_SCENE_MESH_TRACKING_STATE_TRACKING_ANDROID, the
snapshots may: not be up to date or empty.
--

==== Acquiring scene mesh data from the scene mesh snapshot

[open,refpage='xrGetAllSubmeshStatesANDROID',type='protos',desc='Get the info of all submeshes in the scene mesh',xrefs='XrSceneMeshSnapshotANDROID XrSceneSubmeshStateANDROID']
--
The flink:xrGetAllSubmeshStatesANDROID function is defined as:

include::{generated}/api/protos/xrGetAllSubmeshStatesANDROID.adoc[]

.Parameter Descriptions
****
* pname:snapshot is an slink:XrSceneMeshSnapshotANDROID handle previously
  created with flink:xrCreateSceneMeshSnapshotANDROID.
* pname:submeshStateCapacityInput is the capacity of pname:submeshStates, or
  0 to retrieve the required capacity.
* pname:submeshStateCountOutput is a pointer to the count of
  pname:submeshStates written, or a pointer to the required capacity in the
  case that pname:submeshStateCapacityInput is insufficient.
* pname:submeshStates is a pointer to an array of
  slink:XrSceneSubmeshStateANDROID structures to which the runtime will
  output the state of all submeshes in the scene mesh.
  It can: be ename:NULL if pname:submeshStateCapacityInput is 0.
* See <<fundamentals-buffer-size-parameters, Buffer Size Parameters>>
  chapter for a detailed description of retrieving the required
  pname:submeshStates size.
****

The application can: use the flink:xrGetAllSubmeshStatesANDROID function to
get the state of all submeshes in the scene mesh.
This contains basic information information to allow the application to
select submeshes for which the application wants data for.

include::{generated}/validity/protos/xrGetAllSubmeshStatesANDROID.adoc[]
--

[open,refpage='XrSceneSubmeshStateANDROID',type='structs',desc='Information to describe the submesh ',xrefs='xrGetAllSubmeshStatesANDROID']
--
The slink:XrSceneSubmeshStateANDROID structure is defined as:

include::{generated}/api/structs/XrSceneSubmeshStateANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
* pname:submeshId is an slink:XrUuid identifying the submesh.
* pname:lastUpdatedTime is an basetype:XrTime representing the time when the
  submesh was last updated.
* pname:submeshPoseInBaseSpace is an slink:XrPosef representing the pose of
  the submesh in the base space used to create the scene mesh snapshot.
  The pose is also the center of the submesh bounding box.
* pname:bounds is an slink:XrExtent3Df describing the dimensions of the
  bounding box that encloses the submesh.
  This bounds is defined in the base space that was used to create the scene
  mesh handle.

The runtime makes best effort to map pname:submeshId with the region of the
physical space occupied by the submesh.
The Runtimes may: at any time lose this mapping and assign a new UUID to any
subset of the detected submeshes.
In particular runtimes are not required to reuse the same UUIDs for the same
meshes in subsequent application instances.
****

include::{generated}/validity/structs/XrSceneSubmeshStateANDROID.adoc[]
--

[open,refpage='xrGetSubmeshDataANDROID',type='protos',desc='Get the mesh data for the selected submeshes',xrefs='XrSceneSubmeshDataANDROID']
--
The flink:xrGetSubmeshDataANDROID function is defined as:

include::{generated}/api/protos/xrGetSubmeshDataANDROID.adoc[]

.Parameter Descriptions
****
* pname:snapshot is an slink:XrSceneMeshSnapshotANDROID handle previously
  created with flink:xrCreateSceneMeshSnapshotANDROID.
* pname:submeshDataCount is the length of pname:inoutSubmeshData.
* pname:inoutSubmeshData is an application allocated array of
  slink:XrSceneSubmeshDataANDROID in which the runtime populates each
  element with the mesh data associated with the submesh id passed in
  slink:XrSceneSubmeshDataANDROID::pname:submeshId.
****

The application can: use the flink:xrGetSubmeshDataANDROID function to get
batches of submeshes, or all submeshes at once, by passing a list of
slink:XrSceneSubmeshDataANDROID with each
slink:XrSceneSubmeshDataANDROID::pname:submeshId set to the respective id of
the submesh to retrieve.

The slink:XrSceneSubmeshDataANDROID::pname:submeshId must: be unique for
every element in pname:inoutSubmeshData and retrievable by
flink:xrGetAllSubmeshStatesANDROID for the same pname:snapshot.
If the submesh Id is invalid or more than one elements in
pname:inoutSubmeshData have the same submesh id, then the runtime must:
return ename:XR_ERROR_VALIDATION_FAILURE.

pname:submeshDataCount must: be equal or less than the value returned by
flink:xrGetAllSubmeshStatesANDROID::pname:submeshStateCountOutput, otherwise
the runtime must: return ename:XR_ERROR_VALIDATION_FAILURE.

This can: be used in a 2-call idiom to query the vertex and index count for
all of the selected submeshes.

include::{generated}/validity/protos/xrGetSubmeshDataANDROID.adoc[]
--

[open,refpage='XrSceneSubmeshDataANDROID',type='structs',desc='Information to describe the submesh ',xrefs='xrGetSubmeshDataANDROID']
--
The slink:XrSceneSubmeshDataANDROID structure is defined as:

include::{generated}/api/structs/XrSceneSubmeshDataANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
* pname:submeshId is an slink:XrUuid identifying the submesh.
* pname:vertexCapacityInput is the capacity of pname:vertexPositions,
  pname:vertexNormals and pname:vertexSemantics, or 0 to retrieve the
  required capacity.
* pname:vertexCountOutput is a pointer to the count of
  pname:vertexPositions, pname:vertexNormals, and pname:vertexSemantics
  written, or a pointer to the required capacity in the case that
  pname:vertexCapacityInput is insufficient.
* pname:vertexPositions is an array of slink:XrVector3f to which the runtime
  will output the vertex positions of the submesh.
* pname:vertexNormals is an array of slink:XrVector3f to which the runtime
  will output the vertex normals of the submesh.
  This field can: be left ename:NULL if the application created a tracker
  with normals disabled.
* pname:vertexSemantics is an array of code:uint8_t to which the runtime
  will output the vertex semantics of the submesh.
  This field can: be left ename:NULL if the application created a tracker
  with ename:XR_SCENE_MESH_SEMANTIC_LABEL_SET_NONE_ANDROID semantic label
  set.
* pname:indexCapacityInput is the capacity of pname:indices, or 0 to
  retrieve the required capacity.
* pname:indexCountOutput is a pointer to the count of pname:indices written,
  or a pointer to the required capacity in the case that
  pname:vertexCapacityInput is insufficient.
* pname:indices is an array of code:uint32_t to which the runtime will
  output the indices of the submesh.
* See <<fundamentals-buffer-size-parameters, Buffer Size Parameters>>
  chapter for a detailed description of retrieving the required
  pname:vertexPositions, pname:vertexNormals, pname:vertexSemantics, and
  pname:indices size.
****

include::{generated}/validity/structs/XrSceneSubmeshDataANDROID.adoc[]
--

[open,refpage='XrSceneMeshSemanticLabelANDROID',type='enums',desc='Semantic label sets for scene meshing',xrefs='XrSceneSubmeshDataANDROID XrSceneMeshSemanticLabelSetANDROID']
--
The elink:XrSceneMeshSemanticLabelANDROID enumeration is the default set of
semantic labels that can: be used to label mesh vertices to describe which
physical environment surface the mesh vertex is on.
This enum set is represented by the
ename:XR_SCENE_MESH_SEMANTIC_LABEL_SET_DEFAULT_ANDROID value in
elink:XrSceneMeshSemanticLabelSetANDROID.

include::{generated}/api/enums/XrSceneMeshSemanticLabelANDROID.adoc[]

The enums have the following meanings:

include::{generated}/api/enums/XrSceneMeshSemanticLabelANDROID.comments.adoc[]
--

==== Destroy a scene mesh snapshot

[open,refpage='xrDestroySceneMeshSnapshotANDROID',type='protos',desc='Destroys a scene mesh snapshot',xrefs='XrSceneMeshingTrackerANDROID xrCreateSceneMeshSnapshotANDROID XrSceneMeshSnapshotANDROID']
--
The flink:xrDestroySceneMeshSnapshotANDROID function is defined as:

include::{generated}/api/protos/xrDestroySceneMeshSnapshotANDROID.adoc[]

.Parameter Descriptions
****
* pname:snapshot is an slink:XrSceneMeshSnapshotANDROID handle previously
  created with flink:xrCreateSceneMeshSnapshotANDROID that will be destroyed
  by this function.
****

The application can: use the flink:xrDestroySceneMeshSnapshotANDROID
function to destroy a scene mesh snapshot.
Once the handle is destroyed, the application can: no longer use it to get
the submesh info or data.
The handle is automatically destroyed when the tracker is destroyed because
the tracker handle is the parent of the scene mesh snapshot handle.

include::{generated}/validity/protos/xrDestroySceneMeshSnapshotANDROID.adoc[]
--

==== Example code for scene meshing

Following example code demonstrates how to access scene mesh data for
rendering.

[source,cpp]
----
XrInstance instance;  // Created at app startup
XrSystemId systemId;  // Received from xrGetSystem() at app startup
XrSession session;    // Created at app startup
XrSpace appPlaySpace; // Created at app startup

// The function pointers are previously initialized using xrGetInstanceProcAddr.
PFN_xrCreateSceneMeshingTrackerANDROID xrCreateSceneMeshingTrackerANDROID;
PFN_xrDestroySceneMeshingTrackerANDROID xrDestroySceneMeshingTrackerANDROID;
PFN_xrEnumerateSupportedSemanticLabelSetsANDROID xrEnumerateSupportedSemanticLabelSetsANDROID;
PFN_xrCreateSceneMeshSnapshotANDROID xrCreateSceneMeshSnapshotANDROID;
PFN_xrDestroySceneMeshSnapshotANDROID xrDestroySceneMeshSnapshotANDROID;
PFN_xrGetAllSubmeshStatesANDROID xrGetAllSubmeshStatesANDROID;
PFN_xrGetSubmeshDataANDROID xrGetSubmeshDataANDROID;

// Inspect system capability
XrSystemSceneMeshingPropertiesANDROID sceneMeshingProps = {
  .type = XR_TYPE_SYSTEM_SCENE_MESHING_PROPERTIES_ANDROID,
};
XrSystemProperties sysProps = {
  .type = XR_TYPE_SYSTEM_PROPERTIES,
  .next = &sceneMeshingProps
};
CHK_XR(xrGetSystemProperties(instance, systemId, &sysProps));
if (!sceneMeshingProps.supportsSceneMeshing) {
    // scene meshing is not supported.
    return;
}

uint32_t supportedsemanticLabelSetsCount = 0;
xrEnumerateSupportedSemanticLabelSetsANDROID(
  instance, systemId, 0, &supportedsemanticLabelSetsCount, nullptr);
std::vector<XrSceneMeshSemanticLabelSetANDROID> supportedSemanticLabelSets(
  supportedsemanticLabelSetsCount);
xrEnumerateSupportedSemanticLabelSetsANDROID(
  instance, systemId, supportedsemanticLabelSetsCount,
  &supportedsemanticLabelSetsCount, supportedSemanticLabelSets.data());

XrSceneMeshSemanticLabelSetANDROID semanticLabelSet = XR_SCENE_MESH_SEMANTIC_LABEL_SET_NONE_ANDROID;
// Check if system supports XR_SCENE_MESH_SEMANTIC_LABEL_SET_DEFAULT_ANDROID
if (std::find(supportedSemanticLabelSets.begin(), supportedSemanticLabelSets.end(),
              XR_SCENE_MESH_SEMANTIC_LABEL_SET_DEFAULT_ANDROID) !=
    supportedSemanticLabelSets.end()) {
  semanticLabelSet = XR_SCENE_MESH_SEMANTIC_LABEL_SET_DEFAULT_ANDROID;
}

XrSceneMeshingTrackerCreateInfoANDROID trackerCreateInfo = {
  .type = XR_TYPE_SCENE_MESHING_TRACKER_CREATE_INFO_ANDROID,
  .semanticLabelSet = semanticLabelSet,
  .enableNormals = XR_TRUE
};

XrSceneMeshingTrackerANDROID tracker = XR_NULL_HANDLE;
CHK_XR(xrCreateSceneMeshingTrackerANDROID(session, &trackerCreateInfo, &tracker));

XrSceneMeshSnapshotCreationResultANDROID snapshotResult = {
  .type = XR_TYPE_SCENE_MESH_SNAPSHOT_CREATION_RESULT_ANDROID,
  .snapshot = XR_NULL_HANDLE
};
XrSceneMeshSnapshotANDROID& snapshot = snapshotResult.snapshot;
XrSceneMeshSnapshotCreateInfoANDROID createInfo = {
  .type = XR_TYPE_SCENE_MESH_SNAPSHOT_CREATE_INFO_ANDROID
};

// app update loop
while (true) {
  // ...
  // For every frame in frame loop
  // ...

  XrFrameState frameState; // previously returned from xrWaitFrame
  const XrTime time = frameState.predictedDisplayTime;
  XrBoxf box; // populated with the bounding box of the camera frustum

  // ...

  createInfo.baseSpace = appPlaySpace;
  createInfo.time = time;
  createInfo.boundingBox = box;

  // Grab the scene mesh snapshot. This way the app can: know all of the submesh infos,
  // choose the appropriate submeshes for which to get data, allocate the necessary
  // buffer for those submeshes, and then get the data.
  CHK_XR(xrCreateSceneMeshSnapshotANDROID(tracker, &createInfo, &snapshotResult));

  // check the tracking state
  if (snapshotResult.trackingState == XR_SCENE_MESH_TRACKING_STATE_ERROR_ANDROID) {
    // unrecoverable error. Exit the app.
    if (snapshot != XR_NULL_HANDLE) {
      CHK_XR(xrDestroySceneMeshSnapshotANDROID(snapshot));
      snapshot = XR_NULL_HANDLE;
    }
    break;
  } else if (snapshotResult.trackingState != XR_SCENE_MESH_TRACKING_STATE_TRACKING_ANDROID) {
    // The tracker is not tracking. Try again later.
    if (snapshot != XR_NULL_HANDLE) {
      CHK_XR(xrDestroySceneMeshSnapshotANDROID(snapshot));
      snapshot = XR_NULL_HANDLE;
    }
    continue;
  }

  // 2-call idiom for getting submesh states
  std::vector<XrSceneSubmeshStateANDROID> states;
  uint32_t submeshCount = 0;
  CHK_XR(xrGetAllSubmeshStatesANDROID(snapshot, 0, &submeshCount, nullptr));
  states.resize(submeshCount);
  for (XrSceneSubmeshStateANDROID& state : states) {
    state = {.type = XR_TYPE_SCENE_SUBMESH_STATE_ANDROID};
  }
  CHK_XR(xrGetAllSubmeshStatesANDROID(snapshot, submeshCount, &submeshCount, states.data()));

  // To store the poses for the selected submeshes
  std::vector<XrPosef> submeshesPoses;
  submeshesPoses.reserve(submeshCount);

  std::vector<XrSceneSubmeshDataANDROID> submeshes;
  submeshes.reserve(submeshCount);
  // Iterate the states and determine which submeshes the app wants data for
  for (XrSceneSubmeshStateANDROID& state : states) {
    // Modify this bool as necessary by looking at states. Maybe state.lastUpdatedTime
    // is below a threshold or maybe the bounding box does not intersect with camera view
    // frustum (The submesh will be culled).
    bool needed;
    if (needed) {
      // Add the selected submesh to the submeshes list. Set the capacity
      // zero for now since the size of the buffer will be determined later.
      XrSceneSubmeshDataANDROID submesh = {
        .type = XR_TYPE_SCENE_SUBMESH_DATA_ANDROID,
        .submeshId = state.submeshId,
        .vertexCapacityInput = 0,
        .vertexCountOutput = 0,
        .vertexPositions = nullptr,
        .vertexNormals = nullptr,
        .vertexSemantics = nullptr,
        .indexCapacityInput = 0,
        .indexCountOutput = 0,
        .indices = nullptr,
      };
      submeshes.push_back(submesh);
      submeshesPoses.push_back(state.submeshPoseInBaseSpace);
    }
  }

  // Grab the data for the selected submeshes using the 2-call idiom.
  CHK_XR(xrGetSubmeshDataANDROID(snapshot, submeshes.size(), submeshes.data()));
  for (XrSceneSubmeshDataANDROID& submesh : submeshes) {
    submesh.vertexCapacityInput = submesh.vertexCountOutput;
    submesh.vertexCountOutput = 0;
    submesh.vertexPositions = new XrVector3f[submesh.vertexCapacityInput];
    submesh.vertexNormals = new XrVector3f[submesh.vertexCapacityInput];
    submesh.vertexSemantics = new uint8_t[submesh.vertexCapacityInput];
    submesh.indexCapacityInput = submesh.indexCountOutput;
    submesh.indexCountOutput = 0;
    submesh.indices = new uint32_t[submesh.indexCapacityInput];
  }
  CHK_XR(xrGetSubmeshDataANDROID(snapshot, submeshes.size(), submeshes.data()));

  // Destroy the scene mesh snapshot since we have finally grabbed the submeshes data. In
  // next iteration app can: create a new one to get latest mesh data
  CHK_XR(xrDestroySceneMeshSnapshotANDROID(snapshot));
  snapshot = XR_NULL_HANDLE;

  // Iterate the submeshes and get the vertex positions, vertex normals and
  // vertex semantics data for the selected submeshes
  for (uint32_t i = 0; i < submeshes.size(); i++) {
    XrSceneSubmeshDataANDROID& data = submeshes[i];
    XrVector3f* vertexPositions = data.vertexPositions;
    XrVector3f* vertexNormals = data.vertexNormals;
    XrSceneMeshSemanticLabelANDROID* vertexSemantics =
      new XrSceneMeshSemanticLabelANDROID[data.vertexCountOutput];
    for (uint32_t j = 0; j < data.vertexCountOutput; j++) {
      vertexSemantics[j] =
        static_cast<XrSceneMeshSemanticLabelANDROID>(data.vertexSemantics[j]);
    }
    XrPosef pose = submeshesPoses[i];

    // *** Use the data as per needs ***

    // Release the allocated memory for the data buffers when done using
    delete [] vertexSemantics;
    delete [] data.vertexPositions;
    delete [] data.vertexNormals;
    delete [] data.vertexSemantics;
    delete [] data.indices;
  }

  // ...
  // Finish frame loop
  // ...
}

CHK_XR(xrDestroySceneMeshingTrackerANDROID(tracker));
----

include::{generated}/interfaces/XR_ANDROID_scene_meshing.adoc[leveloffset=1]

==== Issues

==== Version History

* Revision 3, 2025-05-15 (Salar Khan)
** Initial extension description
