// Copyright (c) 2023-2026, Google LLC
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/XR_ANDROID_spatial_discovery_raycast.adoc[]

*Last Modified Date*::
    2025-08-12

*IP Status*::
    No known IP claims.

*Contributors*::
    Brian Chen, Google +
    Levana Chen, Google +
    Kyle Chen, Google +
    Nihav Jain, Google +
    Spencer Quin, Google +
    Natalie Fleury, Meta +
    Yuichi Taguchi, Meta +
    Jimmy Alamparambil, ByteDance +
    Zhipeng Liu, ByteDance +

==== Overview

This extension builds on apiext:XR_EXT_spatial_entity and provides raycast
functionality for existing spatial capabilities, such as
ename:XR_SPATIAL_CAPABILITY_PLANE_TRACKING_EXT, to discover spatial
entities.

This extension also introduces a new spatial capability for raycasting
against depth buffer.

[IMPORTANT]
.Permissions
====

Required permissions depending on the capabilities the Android application
uses.
If ename:XR_SPATIAL_CAPABILITY_DEPTH_RAYCAST_ANDROID is used, the
application must: have android.permission.SCENE_UNDERSTANDING_FINE
permission.
If ename:XR_SPATIAL_CAPABILITY_PLANE_TRACKING_EXT is used, the application
must: have android.permission.SCENE_UNDERSTANDING_COARSE permission.
The android.permission.SCENE_UNDERSTANDING_FINE also implies the
android.permission.SCENE_UNDERSTANDING_COARSE permission, if the application
uses both capabilities, the application does not need to request both
permissions separately.

Both android.permission.SCENE_UNDERSTANDING_COARSE and
android.permission.SCENE_UNDERSTANDING_FINE are considered dangerous
permissions.

(protection level: dangerous)
====

==== Runtime Support

If the runtime supports discovery of spatial entities via raycasting, it
must: indicate this by enumerating
ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID in
flink:xrEnumerateSpatialCapabilityComponentTypesEXT for the capabilities
that support discovery by raycast.

If the runtime supports raycasting against the depth buffer, it must:
enumerate ename:XR_SPATIAL_CAPABILITY_DEPTH_RAYCAST_ANDROID in
flink:xrEnumerateSpatialCapabilitiesEXT.

==== Discover spatial entities by raycasting

[open,refpage='XrSpatialRaycastInfoANDROID',type='structs',desc='Raycast Information for spatial entity discovery',xrefs='xrCreateSpatialDiscoverySnapshotAsyncEXT XrSpatialDiscoverySnapshotCreateInfoEXT XrFutureEXT']
--

The slink:XrSpatialRaycastInfoANDROID structure is defined as:

include::{generated}/api/structs/XrSpatialRaycastInfoANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
* pname:space is the slink:XrSpace in which the pose of
  slink:XrSpatialRaycastResultDataANDROID will be located.
* pname:time is an basetype:XrTime at which the pose of
  slink:XrSpatialRaycastResultDataANDROID defined.
* pname:origin is an slink:XrVector3f which describes the origin of the ray.
* pname:direction is an slink:XrVector3f which describes the direction of
  the ray.
* pname:maxDistance is the distance in meters that application can:
  optionally specify to limit the discovery of entities that are within the
  specified distance from the pname:origin, along pname:direction.
****

An application can: include slink:XrSpatialRaycastInfoANDROID in the
slink:XrSpatialDiscoverySnapshotCreateInfoEXT::pname:next chain to discover
spatial entities that intersect with the ray defined in this struct.

If an application uses slink:XrSpatialRaycastInfoANDROID with an
slink:XrSpatialContextEXT that was configured without enabling
ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID for any capability,
the runtime must: return ename:XR_ERROR_SPATIAL_COMPONENT_NOT_ENABLED_EXT
from flink:xrCreateSpatialDiscoverySnapshotAsyncEXT or
flink:xrCreateSpatialRaycastSnapshotANDROID.

The runtime must: include the component data and ids of only those spatial
entities in slink:XrSpatialSnapshotEXT that come from capabilities that
support the ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID
component.

If an application sets pname:maxDistance to a positive value, the runtime
must: not include any hit spatial entities in the snapshot that are more
than pname:maxDistance away from the panme:origin along pname:direction.
If pname:maxDistance is set to 0 or a negative value, the runtime must:
consider the ray unbounded.

include::{generated}/validity/structs/XrSpatialRaycastInfoANDROID.adoc[]
--

==== Raycast Result Component

[open,refpage='XrSpatialRaycastResultDataANDROID',type='structs',desc='Raycast Result',xrefs='XrSpatialComponentRaycastResultListANDROID']
--

The slink:XrSpatialRaycastResultDataANDROID structure is defined as:

include::{generated}/api/structs/XrSpatialRaycastResultDataANDROID.adoc[]

.Member Descriptions
****
* pname:hitPose is an slink:XrPosef defining the point where the ray
  intersects with the spatial entity.
* pname:distanceSquared is the squared of the distance from origin of the
  ray to the intersection point.
****

The ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID component will
only be present in an slink:XrSpatialSnapshotEXT created from
flink:xrCreateSpatialDiscoverySnapshotAsyncEXT where
slink:XrSpatialRaycastInfoANDROID is included in the
slink:XrSpatialDiscoverySnapshotCreateInfoEXT::pname:next chain or in an
slink:XrSpatialSnapshotEXT created from
flink:xrCreateSpatialRaycastSnapshotANDROID.

The runtime must: not include this component in any
slink:XrSpatialSnapshotEXT that is created using
flink:xrCreateSpatialUpdateSnapshotEXT.

The runtime must: return ename:XR_ERROR_VALIDATION_FAILURE from
flink:xrCreateSpatialUpdateSnapshotEXT if the application includes
ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID in
slink:XrSpatialUpdateSnapshotCreateInfoEXT::pname:componentTypes.

If ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID is enabled only
for certain capabilities, the runtime must: include only spatial entities
provided by those capabilities in the snapshot.
For example, if an object and a plane lines up in the same direction and
ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID is enabled only for
ename:XR_SPATIAL_CAPABILITY_PLANE_TRACKING_EXT, only the plane will be
discovered.

The pname:hitPose of the
ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID will be located in
slink:XrCreateSpatialDiscoverySnapshotCompletionInfoEXT::pname:baseSpace at
slink:XrCreateSpatialDiscoverySnapshotCompletionInfoEXT::pname:time.
The positive Z axis is the normal of the hit surface, and the negative Y
axis roughly points toward the ray origin.

include::{generated}/validity/structs/XrSpatialRaycastResultDataANDROID.adoc[]
--

===== Component list struct to query data

[open,refpage='XrSpatialComponentRaycastResultListANDROID',type='structs',desc='List struct for the raycast result component',xrefs='XrSpatialComponentTypeEXT xrQuerySpatialComponentDataEXT XrSpatialComponentDataQueryResultEXT']
--
The slink:XrSpatialComponentRaycastResultListANDROID structure is defined
as:

include::{generated}/api/structs/XrSpatialComponentRaycastResultListANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
* pname:raycastResultCount is a code:uint32_t describing the count of
  elements in the pname:raycastResults array.
* pname:raycastResults is an array of
  slink:XrSpatialRaycastResultDataANDROID.
****

To query the raycast result component of the spatial entities in an
slink:XrSpatialSnapshotEXT, include
ename:XR_TYPE_SPATIAL_COMPONENT_RAYCAST_RESULT_LIST_ANDROID in
slink:XrSpatialComponentDataQueryConditionEXT::pname:componentTypes and add
slink:XrSpatialComponentRaycastResultListANDROID to the
slink:XrSpatialComponentDataQueryResultEXT::pname:next chain.

The runtime must: return ename:XR_ERROR_VALIDATION_FAILURE from
flink:xrQuerySpatialComponentDataEXT if
slink:XrSpatialComponentRaycastResultListANDROID is in the
slink:XrSpatialComponentDataQueryResultEXT::pname:next chain but
ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID is not included in
slink:XrSpatialComponentDataQueryConditionEXT::pname:componentTypes.

The runtime must: return ename:XR_ERROR_SIZE_INSUFFICIENT from
flink:xrQuerySpatialComponentDataEXT if pname:raycastResultCount is less
than slink:XrSpatialComponentDataQueryResultEXT::pname:entityIdCountOutput.

The returned pname:raycastResults are unordered.
An application can: use
slink:XrSpatialRaycastResultDataANDROID::pname:distanceSquared to sort the
results by distance.

include::{generated}/validity/structs/XrSpatialComponentRaycastResultListANDROID.adoc[]
--

===== Configuration

If ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID is enumerated in
slink:XrSpatialCapabilityComponentTypesEXT::pname:componentTypes for some
capability, the application can: enable it by including the enum value in
the
slink:XrSpatialCapabilityConfigurationBaseHeaderEXT::pname:enabledComponents
list.
This component does not require any special configuration to be included in
the next chain of slink:XrSpatialCapabilityConfigurationBaseHeaderEXT.

The runtime must: return ename:XR_ERROR_VALIDATION_FAILURE from
flink:xrCreateSpatialUpdateSnapshotEXT if the application includes
ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID in
slink:XrSpatialUpdateSnapshotCreateInfoEXT::pname:componentTypes.
This component is specific to discovery snapshots.

==== Depth Raycast Spatial Capability
===== Configuration

[open,refpage='XrSpatialCapabilityConfigurationDepthRaycastANDROID',type='structs',desc='Config struct for the depth raycast capability',xrefs='XrSpatialCapabilityConfigurationBaseHeaderEXT XrSpatialContextCreateInfoEXT xrCreateSpatialContextAsyncEXT']
--

The slink:XrSpatialCapabilityConfigurationDepthRaycastANDROID structure is
defined as:

include::{generated}/api/structs/XrSpatialCapabilityConfigurationDepthRaycastANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
* pname:capability is an elink:XrSpatialCapabilityEXT and must: be
  ename:XR_SPATIAL_CAPABILITY_DEPTH_RAYCAST_ANDROID.
* pname:enabledComponentCount is a code:uint32_t describing the count of
  elements in the pname:enabledComponents array.
  It must: be greater than 0.
* pname:enabledComponents is a pointer to an array of
  elink:XrSpatialComponentTypeEXT.
****

Anpplications can: enable the
ename:XR_SPATIAL_CAPABILITY_DEPTH_RAYCAST_ANDROID spatial capability by
including a pointer to an
slink:XrSpatialCapabilityConfigurationDepthRaycastANDROID structure in
slink:XrSpatialContextCreateInfoEXT::pname:capabilityConfigs.

The runtime must: return ename:XR_ERROR_VALIDATION_FAILURE if
pname:capability is not ename:XR_SPATIAL_CAPABILITY_DEPTH_RAYCAST_ANDROID.

The ID of entities discovered via this capability is always
dlink:XR_NULL_SPATIAL_ENTITY_ID_EXT.
This also means that application can: not create an slink:XrSpatialEntityEXT
handle for these entities, and thus they can: not be included in
slink:XrSpatialUpdateSnapshotCreateInfoEXT::pname:entities to create a
update snapshot

include::{generated}/validity/structs/XrSpatialCapabilityConfigurationDepthRaycastANDROID.adoc[]
--

[[android_spatial_discovery_raycast_guaranteed_components]]
===== Guaranteed Components

A runtime that supports ename:XR_SPATIAL_CAPABILITY_DEPTH_RAYCAST_ANDROID,
must: support the following spatial components as guaranteed components of
the entities discovered by this capability and must: enumerate them in
flink:xrEnumerateSpatialCapabilityComponentTypesEXT -

* ename:XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID

==== Synchronous Raycast

[open,refpage='xrCreateSpatialRaycastSnapshotANDROID',type='protos',desc='Synchronous discovery.',xrefs='XrSpatialRaycastSnapshotCreateInfoANDROID']
--
The flink:xrCreateSpatialRaycastSnapshotANDROID function is defined as:

include::{generated}/api/protos/xrCreateSpatialRaycastSnapshotANDROID.adoc[]

.Parameter Descriptions
****
* pname:spatialContext is an slink:XrSpatialContextEXT previously created by
  using flink:xrCreateSpatialContextAsyncEXT.
* pname:createInfo is a pointer to an
  slink:XrSpatialRaycastSnapshotCreateInfoANDROID.
* pname:snapshot is a pointer to an slink:XrSpatialSnapshotEXT.
****

While flink:xrCreateSpatialDiscoverySnapshotAsyncEXT is sufficient for most
use cases, it is considered slow for applications that require instant
raycast results.
flink:xrCreateSpatialRaycastSnapshotANDROID starts a synchronous raycasting
to create a snapshot, which allows applications to start querying raycast
results immediately.

The runtime must: return ename:XR_ERROR_SPATIAL_COMPONENT_NOT_ENABLED_EXT if
any of the elink:XrSpatialComponentTypeEXT in
slink:XrSpatialRaycastSnapshotCreateInfoANDROID::pname:componentTypes are
not enabled for the spatial capabilities passed to
slink:XrSpatialContextCreateInfoEXT::pname:capabilityConfigs when creating
pname:spatialContext.

If the application does not provide a list of spatial component types in
slink:XrSpatialRaycastSnapshotCreateInfoANDROID::pname:componentTypes, the
runtime must: include all the spatial entities in the snapshot that have the
set of components which are enumerated in
slink:XrSpatialCapabilityConfigurationBaseHeaderEXT::enabledComponents for
raycast supported capabilities configured for pname:spatialContext.
The runtime must: include the data for all the enabled components of the
raycast supported capabilities configured for pname:spatialContext.

include::{generated}/validity/protos/xrCreateSpatialRaycastSnapshotANDROID.adoc[]
--

[open,refpage='XrSpatialRaycastSnapshotCreateInfoANDROID',type='structs',desc='Information to synchronously create a snapshot handle via raycast.',xrefs='xrCreateSpatialRaycastSnapshotANDROID']
--
The slink:XrSpatialRaycastSnapshotCreateInfoANDROID structure is defined as:

include::{generated}/api/structs/XrSpatialRaycastSnapshotCreateInfoANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
* pname:componentTypeCount is a code:uint32_t describing the count of
  elements in the pname:componentTypes array.
* pname:componentTypes is an array of elink:XrSpatialComponentTypeEXT.
* pname:raycastInfo is the slink:XrSpatialRaycastInfoANDROID structure
  describing the information of a ray.
****

include::{generated}/validity/structs/XrSpatialRaycastSnapshotCreateInfoANDROID.adoc[]
--

==== Example code

===== Configure Depth Raycast and Plane Tracking Capability

The following example code demonstrates how to create a spatial context with
capabilities that support raycast functionality.
For this example, ename:XR_SPATIAL_CAPABILITY_DEPTH_RAYCAST_ANDROID and
ename:XR_SPATIAL_CAPABILITY_PLANE_TRACKING_EXT are used.

[source,cpp]
----
// Check runtime supported capabilities
uint32_t capabilityCount;
CHK_XR(xrEnumerateSpatialCapabilitiesEXT(instance, systemId, 0, &capabilityCount, nullptr));
std::vector<XrSpatialCapabilityEXT> capabilities(capabilityCount);
CHK_XR(xrEnumerateSpatialCapabilitiesEXT(instance, systemId, capabilityCount, &capabilityCount, capabilities.data()));

if (std::find(capabilities.begin(), capabilities.end(), XR_SPATIAL_CAPABILITY_DEPTH_RAYCAST_ANDROID) == capabilities.end()) {
  return;
}

if (std::find(capabilities.begin(), capabilities.end(), XR_SPATIAL_CAPABILITY_PLANE_TRACKING_EXT) == capabilities.end()) {
  return;
}

// Create capability config for depth raycasting
std::vector<XrSpatialComponentTypeEXT> depthRaycastComponents {
  XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID
};

// Create capability config for depth raycasting
XrSpatialCapabilityConfigurationDepthRaycastANDROID depthRaycastConfig {
  .type = XR_TYPE_SPATIAL_CAPABILITY_CONFIGURATION_DEPTH_RAYCAST_ANDROID,
  .next = nullptr,
  .capability = XR_SPATIAL_CAPABILITY_DEPTH_RAYCAST_ANDROID,
  .enabledComponentCount = (uint32_t)depthRaycastComponents.size(),
  .enabledComponents = depthRaycastComponents.data(),
};

// Enumerate runtime supported components for plane tracking capability
XrSpatialCapabilityComponentTypesEXT capabilityComponentTypes {
  XR_TYPE_SPATIAL_CAPABILITY_COMPONENT_TYPES_EXT
};

bool isRaycastSupportedViaPlaneTracking;
std::vector<XrSpatialComponentTypeEXT> planeTrackingComponents {
  XR_SPATIAL_COMPONENT_TYPE_BOUNDED_2D_EXT,
  XR_SPATIAL_COMPONENT_TYPE_PLANE_ALIGNMENT_EXT,
};

CHK_XR(xrEnumerateSpatialCapabilityComponentTypesEXT(instance, systemId,
       XR_SPATIAL_CAPABILITY_PLANE_TRACKING_EXT, &capabilityComponentTypes));

planeTrackingComponents.resize(capabilityComponentTypes.componentTypeCountOutput);
capabilityComponentTypes.componentTypeCapacityInput = (uint32_t)planeTrackingComponents.size();
capabilityComponentTypes.componentTypes = planeTrackingComponents.data();

CHK_XR(xrEnumerateSpatialCapabilityComponentTypesEXT(instance, systemId,
       XR_SPATIAL_CAPABILITY_PLANE_TRACKING_EXT, &capabilityComponentTypes));

// Check if raycast is supported by plane tracking
isRaycastSupportedViaPlaneTracking = std::find(planeTrackingComponents.begin(),
planeTrackingComponents.end(), XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID)
!= planeTrackingComponents.end();

// Create capability config for plane tracking
XrSpatialCapabilityConfigurationPlaneTrackingEXT planeTrackingConfig {
  .type = XR_TYPE_SPATIAL_CAPABILITY_CONFIGURATION_PLANE_TRACKING_EXT,
  .next = nullptr,
  .capability = XR_SPATIAL_CAPABILITY_PLANE_TRACKING_EXT,
  .enabledComponentCount = (uint32_t)planeTrackingComponents.size(),
  .enabledComponents = planeTrackingComponents.data(),
};

// Create spatial context
// Types of raycast is determined by configs included in XrSpatialContextCreateInfoEXT
// For this example, both plane raycast & depth raycast are performed
std::vector<const XrSpatialCapabilityConfigurationBaseHeaderEXT*> capabilityConfigs;
capabilityConfigs.push_back(reinterpret_cast<const XrSpatialCapabilityConfigurationBaseHeaderEXT*>(&depthRaycastConfig));
if(isRaycastSupportedViaPlaneTracking) capabilityConfigs.push_back(reinterpret_cast<const XrSpatialCapabilityConfigurationBaseHeaderEXT*>(&planeTrackingConfig));

XrSpatialContextCreateInfoEXT contextCreateInfo{
  .type = XR_TYPE_SPATIAL_CONTEXT_CREATE_INFO_EXT,
  .next = nullptr,
  .capabilityConfigCount = (uint32_t)capabilityConfigs.size(),
  .capabilityConfigs = capabilityConfigs.data(),
};

CHK_XR(xrCreateSpatialContextAsyncEXT(session, &contextCreateInfo, &future))

// Completes creating spatial context
XrCreateSpatialContextCompletionEXT contextCompletion{
XR_TYPE_CREATE_SPATIAL_CONTEXT_COMPLETION_EXT};

CHK_XR(xrCreateSpatialContextCompleteEXT(session, future, &contextCompletion))
----

===== Discover Spatial Entities & Query Component Data

The following example code demonstrates how to discover spatial entities for
a context configured with ename:XR_SPATIAL_CAPABILITY_DEPTH_RAYCAST_ANDROID
& ename:XR_SPATIAL_CAPABILITY_PLANE_TRACKING_EXT and query its component
data.

[source,cpp]
----
// Fill in the raycast info.
XrSpatialRaycastInfoANDROID raycastInfo {
  .type        = XR_TYPE_SPATIAL_RAYCAST_INFO_ANDROID,
  .next        = nullptr,
  .space       = viewSpace,
  .time        = updateTime,
  .origin      = {0.0f, 0.0f, 0.0f},
  .direction   = {0.0f, 0.0f,-1.0f},
  .maxDistance = 0.0f  // ray is unbounded
};

// Next pointing to the raycast info.
XrSpatialDiscoverySnapshotCreateInfoEXT discoverySnapshotCreateInfo {
  .type = XR_TYPE_SPATIAL_DISCOVERY_SNAPSHOT_CREATE_INFO_EXT,
  .next = &raycastInfo
};

// Create snapshot
CHK_XR(xrCreateSpatialDiscoverySnapshotAsyncEXT (
spatialContext, &discoverySnapshotCreateInfo, &future));

waitUntilReady(future);

// Complete async operation.
XrCreateSpatialDiscoverySnapshotCompletionInfoEXT
  createSnapshotCompletionInfo {
    .type      = XR_TYPE_CREATE_SPATIAL_DISCOVERY_SNAPSHOT_COMPLETION_INFO_EXT,
    .baseSpace = viewSpace,
    .time      = updateTime,
    .future    = future,
  };

XrCreateSpatialDiscoverySnapshotCompletionEXT completion {
  XR_TYPE_CREATE_SPATIAL_DISCOVERY_SNAPSHOT_COMPLETION_EXT};

CHK_XR(xrCreateSpatialDiscoverySnapshotCompleteEXT(
           spatialContext, &createSnapshotCompletionInfo,
           &completion));

if(completion.futureResult != XR_SUCCESS) return;

// Query hit result components
std::array<XrSpatialComponentTypeEXT, 1> enabledComponents = {
  XR_SPATIAL_COMPONENT_TYPE_RAYCAST_RESULT_ANDROID
};

XrSpatialComponentDataQueryConditionEXT queryCond {
  .type = XR_TYPE_SPATIAL_COMPONENT_DATA_QUERY_CONDITION_EXT,
  .componentTypeCount = 1,
  .componentTypes     = enabledComponents.data(),
};

XrSpatialComponentDataQueryResultEXT queryResult {
  .type = XR_TYPE_SPATIAL_COMPONENT_DATA_QUERY_RESULT_EXT,
};

XrResult result = xrQuerySpatialComponentDataEXT(
           completion.snapshot, &queryCond, &queryResult);

// Check query result.
if(result != XR_SUCCESS) return;

// Query again for the hit result list.
std::vector<XrSpatialRaycastResultDataANDROID> raycastResults;
raycastResults.resize(queryResult.entityIdCountOutput);
XrSpatialComponentRaycastResultListANDROID raycastResultList {
  .type               = XR_TYPE_SPATIAL_COMPONENT_RAYCAST_RESULT_LIST_ANDROID,
  .raycastResultCount = (uint32_t)raycastResults.size(),
  .raycastResults     = raycastResults.data(),
};

queryResult.next = &raycastResultList;
result = xrQuerySpatialComponentDataEXT(completion.snapshot, &queryCond, &queryResult);

// Check query result again.
if(result != XR_SUCCESS) return;

std::vector<XrSpatialEntityEXT> hitEntities;
std::vector<XrPosef> depthHitPoses;
for(uint32_t i = 0; i < queryResult.entityIdCountOutput; ++i) {
	// access raycastResults[i] for id & pose
	XrSpatialEntityIdEXT   id   = queryResult.entityIds[i];
	XrPosef                pose = raycastResults[i].hitPose;

	if (id != XR_NULL_SPATIAL_ENTITY_ID_EXT) {
		// hit entities (e.g. planes)
    // get entity handle via entity id
    XrSpatialEntityFromIdCreateInfoEXT entityCreateInfo {
      .type = XR_TYPE_SPATIAL_ENTITY_FROM_ID_CREATE_INFO_EXT,
      .entityId = id,
    };

    XrSpatialEntityEXT entity = XR_NULL_HANDLE;
    xrCreateSpatialEntityFromIdEXT(spatialContext, &entityCreateInfo, &entity);

    hitEntities.push_back(entity);
  } else {
    // hit depth
    depthHitPoses.push_back(pose);
  }
}

// Cleanup
xrDestroySpatialSnapshotEXT(completion.snapshot);
----

===== Create Raycast Snapshot

The following example code demonstrates how to create synchronous raycast
snapshot.

[source,cpp]
----
// fill in create info
XrSpatialRaycastSnapshotCreateInfoANDROID createInfo {
  .type = XR_TYPE_SPATIAL_RAYCAST_SNAPSHOT_CREATE_INFO_ANDROID,
  .componentTypeCount = 0,   // include all hit spatial entities
  .componentTypes = nullptr,
  .raycastInfo = &raycastInfo
};

// create raycast snapshot
XrSpatialSnapshotEXT raycastSnapshot = XR_NULL_HANDLE;
CHK_XR(xrCreateSpatialRaycastSnapshotANDROID(
  spatialContext, &createInfo, &raycastSnapshot));

// ...
// query component data as previous example
// ...

// Cleanup
xrDestroySpatialSnapshotEXT(raycastSnapshot);

----

include::{generated}/interfaces/XR_ANDROID_spatial_discovery_raycast.adoc[leveloffset=1]

==== Issues

==== Version History

* Revision 1, 2025-07-15 (Brian Chen)
** Initial extension description.
