// Copyright (c) 2023-2026, Google LLC
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/XR_ANDROID_geospatial_anchor.adoc[]

*Last Modified Date*::
    2025-10-30
*IP Status*::
    No known IP claims.
*Contributors*::
    John Ullman, Google +
    Ben King, Google +
    Nihav Jain, Google +
    Jared Finder, Google +

==== Overview

This extension provides Geospatial Anchors and Surface Anchors that build on
the base Geospatial extension.
Geospatial Anchors are anchors that are positioned in space relative to the
Earth at a given latitude, longitude and altitude.
Surface Anchors are Earth-relative anchors which are placed at a given
latitude, longitude, and altitude relative to a surface as known by the
Visual Positioning Service.
As the runtime's accuracy of its position relative to the Earth improves,
the Anchor's pose will adjust accordingly.


==== System Capability for Geospatial Anchors

[open,refpage='XrSystemGeospatialAnchorPropertiesANDROID',type='structs',desc='System property for geospatial anchors',xrefs='XrSystemProperties xrGetSystemProperties']
--
The slink:XrSystemGeospatialAnchorPropertiesANDROID structure is defined as:

include::{generated}/api/structs/XrSystemGeospatialAnchorPropertiesANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
* pname:maxSurfaceAnchorCount is a code:uint32_t indicating the maximum
  number of surface anchors that can: be created.
****

An application can: inspect geospatial anchor capabilities of the system by
chaining an slink:XrSystemGeospatialAnchorPropertiesANDROID structure to the
slink:XrSystemProperties when calling flink:xrGetSystemProperties.

If slink:XrSystemGeospatialPropertiesANDROID::pname:supportsGeospatial is
ename:XR_TRUE, then pname:maxSurfaceAnchorCount indicates the maximum number
of surface anchors the runtime supports.
The limit must: be greater than 0 in this case.

If slink:XrSystemGeospatialPropertiesANDROID::pname:supportsGeospatial is
not ename:XR_TRUE, then pname:maxSurfaceAnchorCount must: be 0.

include::{generated}/validity/structs/XrSystemGeospatialAnchorPropertiesANDROID.adoc[]
--

==== Plane Tracking for Anchors

[open,refpage='XrGeospatialTrackerAnchorTrackingInfoANDROID',type='structs',desc='Information to configure anchor tracking for a geospatial tracker',xrefs='XrGeospatialTrackerCreateInfoANDROID']
--
The slink:XrGeospatialTrackerAnchorTrackingInfoANDROID structure is defined
as:

include::{generated}/api/structs/XrGeospatialTrackerAnchorTrackingInfoANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
* pname:shouldTrackPlanes is an basetype:XrBool32 indicating if the
  geospatial tracker will track planes to improve positioning of
  surface-locked anchors.
****

Plane tracking can: be enabled to improve positioning of surface-locked
anchors.

If the application wants to enable plane tracking to improve surface anchor
poses, it can: chain an slink:XrGeospatialTrackerAnchorTrackingInfoANDROID
structure to slink:XrGeospatialTrackerCreateInfoANDROID when calling
flink:xrCreateGeospatialTrackerANDROID.

include::{generated}/validity/structs/XrGeospatialTrackerAnchorTrackingInfoANDROID.adoc[]
--

==== Geospatial Anchors

[open,refpage='xrCreateGeospatialAnchorANDROID',type='protos',desc='Create a geospatial anchor',xrefs='XrGeospatialAnchorCreateInfoANDROID']
--
The flink:xrCreateGeospatialAnchorANDROID function is defined as:

include::{generated}/api/protos/xrCreateGeospatialAnchorANDROID.adoc[]

.Parameter Descriptions
****
* pname:spatialContext is the slink:XrSpatialContextEXT to create the anchor
  in.
  The context must: be configured for ename:XR_SPATIAL_CAPABILITY_ANCHOR_EXT
  otherwise the runtime must: return ename:XR_ERROR_VALIDATION_FAILURE.
* pname:createInfo is a pointer to slink:XrGeospatialAnchorCreateInfoANDROID
  containing anchor creation parameters.
* pname:anchorEntityId is a pointer to basetype:XrSpatialEntityIdEXT in
  which the anchor entity ID is returned.
****

If the slink:XrGeospatialTrackerANDROID specified in
slink:XrGeospatialAnchorCreateInfoANDROID::pname:geospatialTracker is not in
the ename:XR_GEOSPATIAL_TRACKER_STATE_RUNNING_ANDROID state, the runtime
must: return ename:XR_ERROR_GEOSPATIAL_TRACKER_NOT_RUNNING_ANDROID.

include::{generated}/validity/protos/xrCreateGeospatialAnchorANDROID.adoc[]
--

[open,refpage='XrGeospatialAnchorCreateInfoANDROID',type='structs',desc='Information to create a geospatial anchor',xrefs='xrCreateGeospatialAnchorANDROID']
--
The slink:XrGeospatialAnchorCreateInfoANDROID structure is defined as:

include::{generated}/api/structs/XrGeospatialAnchorCreateInfoANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
* pname:geospatialTracker is the slink:XrGeospatialTrackerANDROID to use for
  creating the anchor.
* pname:geospatialPose is a pointer to slink:XrGeospatialPoseANDROID
  defining the anchor's location and orientation.
****

include::{generated}/validity/structs/XrGeospatialAnchorCreateInfoANDROID.adoc[]
--

==== Surface Anchors

Surface anchors are anchors placed relative to a surface, such as terrain or
rooftops.

[open,refpage='XrSurfaceAnchorTypeANDROID',type='enums',desc='Type of surface anchor',xrefs='XrSurfaceAnchorCreateInfoANDROID']
--
The elink:XrSurfaceAnchorTypeANDROID enumeration is defined as:

include::{generated}/api/enums/XrSurfaceAnchorTypeANDROID.adoc[]

The elink:XrSurfaceAnchorTypeANDROID enumeration specifies the type of
surface an anchor is relative to.

The enumerants have the following values:

include::{generated}/api/enums/XrSurfaceAnchorTypeANDROID.comments.adoc[]
--

[open,refpage='xrCreateSurfaceAnchorAsyncANDROID',type='protos',desc='Asynchronously create a surface anchor',xrefs='XrSurfaceAnchorCreateInfoANDROID']
--
The flink:xrCreateSurfaceAnchorAsyncANDROID function is defined as:

include::{generated}/api/protos/xrCreateSurfaceAnchorAsyncANDROID.adoc[]

.Parameter Descriptions
****
* pname:spatialContext is the slink:XrSpatialContextEXT to create the anchor
  in.
* pname:createInfo is a pointer to slink:XrSurfaceAnchorCreateInfoANDROID
  containing anchor creation parameters.
* pname:future is a pointer to basetype:XrFutureEXT that will hold the
  result of the asynchronous operation.
****

The flink:xrCreateSurfaceAnchorAsyncANDROID function begins an asynchronous
operation to create a surface anchor.
Unlike standard geospatial anchors, the runtime may: fetch terrain data to
determine the correct altitude.
The runtime must: return ename:XR_ERROR_LIMIT_REACHED if the application
attempts to create more than
slink:XrSystemGeospatialAnchorPropertiesANDROID::pname:maxSurfaceAnchorCount
surface anchors at a time.
If the slink:XrGeospatialTrackerANDROID specified in
slink:XrSurfaceAnchorCreateInfoANDROID::pname:geospatialTracker is not in
the ename:XR_GEOSPATIAL_TRACKER_STATE_RUNNING_ANDROID state, the runtime
must: return ename:XR_ERROR_GEOSPATIAL_TRACKER_NOT_RUNNING_ANDROID.
The operation may: fail asynchronously with result
ename:XR_ERROR_SURFACE_ANCHOR_LOCATION_UNSUPPORTED_ANDROID if there is no
surface data for the given location.
The runtime must: return ename:XR_ERROR_VALIDATION_FAILURE if
ename:XR_SPATIAL_CAPABILITY_ANCHOR_EXT was not configured for
pname:spatialContext.


include::{generated}/validity/protos/xrCreateSurfaceAnchorAsyncANDROID.adoc[]
--

[open,refpage='XrSurfaceAnchorCreateInfoANDROID',type='structs',desc='Information to create a surface anchor',xrefs='xrCreateSurfaceAnchorAsyncANDROID']
--
The slink:XrSurfaceAnchorCreateInfoANDROID structure is defined as:

include::{generated}/api/structs/XrSurfaceAnchorCreateInfoANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
* pname:geospatialTracker is the slink:XrGeospatialTrackerANDROID to use.
* pname:surfaceAnchorType is the elink:XrSurfaceAnchorTypeANDROID for the
  anchor.
* pname:eastUpSouthOrientation is the orientation with respect to a
  coordinate system where +X=East, +Y=Up and +Z=South.
* pname:latitude is the latitude in degrees, between -89.9 and +89.9.
* pname:longitude is the longitude in degrees, between -180 and +180.
* pname:altitudeRelativeToSurface is the altitude in meters relative to the
  surface specified by pname:surfaceAnchorType.
****

include::{generated}/validity/structs/XrSurfaceAnchorCreateInfoANDROID.adoc[]
--

[open,refpage='xrCreateSurfaceAnchorCompleteANDROID',type='protos',desc='Complete asynchronous surface anchor creation',xrefs='XrSurfaceAnchorCreateCompletionANDROID']
--
The flink:xrCreateSurfaceAnchorCompleteANDROID function is defined as:

include::{generated}/api/protos/xrCreateSurfaceAnchorCompleteANDROID.adoc[]

.Parameter Descriptions
****
* pname:spatialContext is the slink:XrSpatialContextEXT used for creation.
* pname:future is the basetype:XrFutureEXT returned by
  flink:xrCreateSurfaceAnchorAsyncANDROID.
* pname:completion is a pointer to
  slink:XrSurfaceAnchorCreateCompletionANDROID that receives the result.
****

include::{generated}/validity/protos/xrCreateSurfaceAnchorCompleteANDROID.adoc[]
--

[open,refpage='XrSurfaceAnchorCreateCompletionANDROID',type='structs',desc='Result of surface anchor creation',xrefs='xrCreateSurfaceAnchorCompleteANDROID']
--
The slink:XrSurfaceAnchorCreateCompletionANDROID structure holds the result
of an asynchronous surface anchor creation.

include::{generated}/api/structs/XrSurfaceAnchorCreateCompletionANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
* pname:futureResult is the elink:XrResult of the creation operation.
  If pname:futureResult is
  ename:XR_ERROR_GEOSPATIAL_CLOUD_AUTH_FAILED_ANDROID, a structure in the
  pname:next chain may: provide more information about the failure.
* pname:anchorEntityId is the basetype:XrSpatialEntityIdEXT of the created
  anchor, or dlink:XR_NULL_SPATIAL_ENTITY_ID_EXT if pname:futureResult is
  not ename:XR_SUCCESS.
****

.Future Return Codes
****
pname:futureResult values:

<<fundamentals-successcodes,Success>>::
* ename:XR_SUCCESS
* ename:XR_SESSION_LOSS_PENDING

<<fundamentals-errorcodes,Failure>>::
* ename:XR_ERROR_RUNTIME_FAILURE
* ename:XR_ERROR_INSTANCE_LOST
* ename:XR_ERROR_SESSION_LOST
* ename:XR_ERROR_OUT_OF_MEMORY
* ename:XR_ERROR_LIMIT_REACHED
* ename:XR_ERROR_GEOSPATIAL_TRACKER_NOT_RUNNING_ANDROID
* ename:XR_ERROR_SURFACE_ANCHOR_LOCATION_UNSUPPORTED_ANDROID
* ename:XR_ERROR_GEOSPATIAL_CLOUD_AUTH_FAILED_ANDROID
****

include::{generated}/validity/structs/XrSurfaceAnchorCreateCompletionANDROID.adoc[]
--

==== Example

===== Create Terrain Anchor
[source,cpp]
----
PFN_xrCreateSpatialContextAsyncEXT xrCreateSpatialContextAsyncEXT;
PFN_xrCreateSpatialContextCompleteEXT xrCreateSpatialContextCompleteEXT;
PFN_xrCreateSurfaceAnchorAsyncANDROID xrCreateSurfaceAnchorAsyncANDROID;
PFN_xrPollFutureEXT xrPollFutureEXT;
PFN_xrCreateSurfaceAnchorCompleteANDROID xrCreateSurfaceAnchorCompleteANDROID;
XrInstance instance;
XrSession session;
XrGeospatialTrackerANDROID geospatialTracker;

// Create a spatial context
XrSpatialContextEXT spatialContext{};
{
  std::vector<XrSpatialComponentTypeEXT> enabledComponents = {
    XR_SPATIAL_COMPONENT_TYPE_ANCHOR_EXT,
  };

  XrSpatialCapabilityConfigurationAnchorEXT anchorConfig {
    .type = XR_TYPE_SPATIAL_CAPABILITY_CONFIGURATION_ANCHOR_EXT,
    .capability = XR_SPATIAL_CAPABILITY_ANCHOR_EXT,
    .enabledComponentCount = static_cast<uint32_t>(enabledComponents.size()),
    .enabledComponents = enabledComponents.data(),
  };

  std::array<XrSpatialCapabilityConfigurationBaseHeaderEXT*, 1> capabilityConfigs = {
    reinterpret_cast<XrSpatialCapabilityConfigurationBaseHeaderEXT*>(&anchorConfig),
  };

  XrSpatialContextCreateInfoEXT spatialContextCreateInfo {
    .type = XR_TYPE_SPATIAL_CONTEXT_CREATE_INFO_EXT,
    .capabilityConfigCount = capabilityConfigs.size(),
    .capabilityConfigs = capabilityConfigs.data(),
  };
  XrFutureEXT createContextFuture {XR_NULL_FUTURE_EXT};
  CHK_XR(xrCreateSpatialContextAsyncEXT(session, &spatialContextCreateInfo, &createContextFuture));

  // ... wait until future is ready ...

  XrCreateSpatialContextCompletionEXT contextCompletion{
    .type = XR_TYPE_CREATE_SPATIAL_CONTEXT_COMPLETION_EXT,
  };
  CHK_XR(xrCreateSpatialContextCompleteEXT(session, createContextFuture, &contextCompletion));
  if (contextCompletion.futureResult != XR_SUCCESS) {
    return;
  }

  spatialContext = contextCompletion.spatialContext;
}

XrSurfaceAnchorCreateInfoANDROID anchorCreateInfo {
  .type = XR_TYPE_SURFACE_ANCHOR_CREATE_INFO_ANDROID,
  .geospatialTracker = geospatialTracker,
  .surfaceAnchorType = XR_SURFACE_ANCHOR_TYPE_TERRAIN_ANDROID,
  .eastUpSouthOrientation = {0, 0, 0, 1},
  .latitude = 37.7749,
  .longitude = -122.4194,
  .altitudeRelativeToSurface = 0,
};
XrFutureEXT anchorFuture {XR_NULL_FUTURE_EXT};
CHK_XR(xrCreateSurfaceAnchorAsyncANDROID(spatialContext, &anchorCreateInfo, &anchorFuture));

XrFuturePollInfoEXT anchorPollInfo{
  .type = XR_TYPE_FUTURE_POLL_INFO_EXT,
  .future = anchorFuture,
};
XrFuturePollResultEXT anchorPollResult{
  .type = XR_TYPE_FUTURE_POLL_RESULT_EXT,
  .state = XR_FUTURE_STATE_PENDING_EXT,
};
while (anchorPollResult.state == XR_FUTURE_STATE_PENDING_EXT) {
  // Do in render loop/state loop.
  CHK_XR(xrPollFutureEXT(instance, &anchorPollInfo, &anchorPollResult));
}

XrSurfaceAnchorCreateCompletionANDROID anchorCompletion{
  .type = XR_TYPE_SURFACE_ANCHOR_CREATE_COMPLETION_ANDROID,
};
CHK_XR(xrCreateSurfaceAnchorCompleteANDROID(spatialContext, anchorFuture, &anchorCompletion));
if (anchorCompletion.futureResult == XR_SUCCESS) {
  // Use completion.anchorEntityId.
  XrSpatialEntityIdEXT anchorId = anchorCompletion.anchorEntityId;

  // Query in UpdateSnapshot.
}
----

include::{generated}/interfaces/XR_ANDROID_geospatial_anchor.adoc[leveloffset=1]

==== Issues

==== Version History

* Revision 1, 2025-10-30 (Ben King)
** Initial draft.
