// Copyright (c) 2023-2026, Google LLC
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/XR_ANDROID_light_estimation.adoc[]

*Last Modified Date*::
    2025-03-13

*IP Status*::
    No known IP claims.

*Contributors*::
    Jared Finder, Google +
    Cairn Overturf, Google +
    Spencer Quin, Google +
    Levana Chen, Google +
    Nihav Jain, Google +
    Salar Khan, Google +
    Scott Chung, Google +

==== Overview

This extension allows the application to request data representing the
lighting of the real-world environment around the headset.
The application can: use this information to light virtual objects under the
same conditions as the real-world scene they're placed in.

[IMPORTANT]
.Permissions
====
Android applications must: have the
android.permission.SCENE_UNDERSTANDING_COARSE permission listed in their
manifest as this extension exposes lighting information about the
environment.
The android.permission.SCENE_UNDERSTANDING_COARSE permission is considered a
dangerous permission.
The application must: request the permission at runtime to use these
functions:

* flink:xrCreateLightEstimatorANDROID

(protection level: dangerous)
====

==== Inspect system capability

[open,refpage='XrSystemLightEstimationPropertiesANDROID',type='structs',desc='System property for light estimation',xrefs='XrSystemProperties xrGetSystemProperties']
--
The slink:XrSystemLightEstimationPropertiesANDROID structure is defined as:

include::{generated}/api/structs/XrSystemLightEstimationPropertiesANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
* pname:supportsLightEstimation is an basetype:XrBool32, indicating if the
  current system supports light estimation.
****

An application can: inspect whether the system is capable of supporting
light estimation by extending the slink:XrSystemProperties with
slink:XrSystemLightEstimationPropertiesANDROID structure when calling
flink:xrGetSystemProperties.

If and only if a runtime returns ename:XR_FALSE for
pname:supportsLightEstimation, the runtime must: return
ename:XR_ERROR_FEATURE_UNSUPPORTED from flink:xrCreateLightEstimatorANDROID.

include::{generated}/validity/structs/XrSystemLightEstimationPropertiesANDROID.adoc[]
--

==== Create a light estimator handle

[open,refpage='XrLightEstimatorANDROID',type='handles',desc='XrLightEstimatorANDROID', xrefs='xrCreateLightEstimatorANDROID xrDestroyLightEstimatorANDROID xrGetLightEstimateANDROID']
--
include::{generated}/api/handles/XrLightEstimatorANDROID.adoc[]

The light estimation data is generated by the runtime and shared with the
application using the slink:XrLightEstimatorANDROID handle.

This handle can: be used to access light estimation information using other
functions in this extension.
--

[open,refpage='xrCreateLightEstimatorANDROID',desc='Creates a light estimator',type='protos',xrefs='XrLightEstimatorCreateInfoANDROID']
--
The flink:xrCreateLightEstimatorANDROID function is defined as:

include::{generated}/api/protos/xrCreateLightEstimatorANDROID.adoc[]

.Parameter Descriptions
****
* pname:session is the slink:XrSession that creates the light estimator.
* pname:createInfo is a pointer to an
  slink:XrLightEstimatorCreateInfoANDROID structure containing parameters to
  be used to create the light estimator.
* pname:outHandle is a pointer to a handle in which the created
  slink:XrLightEstimatorANDROID is returned.
****

The application uses the flink:xrCreateLightEstimatorANDROID function to
create a light estimator.

* The runtime must: return ename:XR_ERROR_FEATURE_UNSUPPORTED if the system
  does not support light estimation.
* The runtime must: return ename:XR_ERROR_PERMISSION_INSUFFICIENT if the
  required permissions have not been granted to the calling app.

If an application wants to indicate to the runtime that it is done accessing
light estimation data it must: destroy the handle via
flink:xrDestroyLightEstimatorANDROID.

include::{generated}/validity/protos/xrCreateLightEstimatorANDROID.adoc[]
--

[open,refpage='XrLightEstimatorCreateInfoANDROID',type='structs',desc='Information to create a light estimator',xrefs='xrCreateLightEstimatorANDROID XrLightEstimatorANDROID']
--
The slink:XrLightEstimatorCreateInfoANDROID structure describes the
information to create an slink:XrLightEstimatorANDROID handle.

include::{generated}/api/structs/XrLightEstimatorCreateInfoANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  No such structures are defined in core OpenXR or this extension.
****

include::{generated}/validity/structs/XrLightEstimatorCreateInfoANDROID.adoc[]
--

[open,refpage='xrDestroyLightEstimatorANDROID',type='protos',desc='Destroy a light estimator handle',xrefs='xrCreateLightEstimatorANDROID XrLightEstimatorANDROID']
--
The flink:xrDestroyLightEstimatorANDROID function is defined as:

include::{generated}/api/protos/xrDestroyLightEstimatorANDROID.adoc[]

.Parameter Descriptions
****
* pname:estimator is an slink:XrLightEstimatorANDROID previously created by
  flink:xrCreateLightEstimatorANDROID.
****

The flink:xrDestroyLightEstimatorANDROID function releases the
pname:estimator and any underlying resources.

include::{generated}/validity/protos/xrDestroyLightEstimatorANDROID.adoc[]
--

==== Access light estimation data

[open,refpage='xrGetLightEstimateANDROID',desc='Gets estimate of lighting information from a light estimator',type='protos',xrefs='XrLightEstimatorANDROID XrLightEstimateGetInfoANDROID XrLightEstimateANDROID']
--
The flink:xrGetLightEstimateANDROID function is defined as:
include::{generated}/api/protos/xrGetLightEstimateANDROID.adoc[]

.Parameter Descriptions
****
* pname:estimator is a handle to an slink:XrLightEstimatorANDROID previously
  created with flink:xrCreateLightEstimatorANDROID.
* pname:input is a pointer to an slink:XrLightEstimateGetInfoANDROID
  structure.
* pname:output is a pointer to an slink:XrLightEstimateANDROID structure.
****

include::{generated}/validity/protos/xrGetLightEstimateANDROID.adoc[]
--

[open,refpage='XrLightEstimateGetInfoANDROID',type='structs',desc='Information to get light estimation data',xrefs='xrGetLightEstimateANDROID']
--
The slink:XrLightEstimateGetInfoANDROID structure is defined as:

include::{generated}/api/structs/XrLightEstimateGetInfoANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
* pname:space is the slink:XrSpace defining the reference space in which the
  returned light direction and spherical harmonics are expressed in.
* pname:time is the basetype:XrTime that describes the time at which the
  application wishes to query the light estimation.
****

include::{generated}/validity/structs/XrLightEstimateGetInfoANDROID.adoc[]
--

[open,refpage='XrLightEstimateANDROID',type='structs',desc='Contains information about light estimation',xrefs='xrGetLightEstimateANDROID XrAmbientLightANDROID XrSphericalHarmonicsANDROID XrDirectionalLightANDROID']
--
The slink:XrLightEstimateANDROID structure contains light estimation data:

include::{generated}/api/structs/XrLightEstimateANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  Valid structures include slink:XrAmbientLightANDROID,
  slink:XrSphericalHarmonicsANDROID, and slink:XrDirectionalLightANDROID.
* pname:state is the elink:XrLightEstimateStateANDROID representing the
  state of the light estimate.
* pname:lastUpdatedTime is the basetype:XrTime that represents when the
  estimate was last calculated.
****

For every light estimate struct if the pname:state is
ename:XR_LIGHT_ESTIMATE_STATE_INVALID_ANDROID, then all other fields in the
struct are arbitrary, meaning their values are undefined.

To obtain light estimate information for ambient light, spherical harmonics
and the primary directional light, applications can: chain instances of the
following structures, slink:XrAmbientLightANDROID,
slink:XrSphericalHarmonicsANDROID, and slink:XrDirectionalLightANDROID
respectively to slink:XrLightEstimateANDROID::pname:next.

include::{generated}/validity/structs/XrLightEstimateANDROID.adoc[]
--

[open,refpage='XrAmbientLightANDROID',type='structs',desc='Contains information about light estimation',xrefs='xrGetLightEstimateANDROID XrSphericalHarmonicsANDROID XrDirectionalLightANDROID']
--
The slink:XrAmbientLightANDROID structure contains light estimation data
about the ambient light in the scene.

include::{generated}/api/structs/XrAmbientLightANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  Valid structures include slink:XrSphericalHarmonicsANDROID and
  slink:XrDirectionalLightANDROID.
* pname:state is the elink:XrLightEstimateStateANDROID representing the
  state of the light estimate.
* pname:intensity is an slink:XrVector3f representing the intensity of the
  ambient light.
  Each component of the vector corresponds to the red, green, and blue
  channels respectively.
* pname:colorCorrection is an slink:XrVector3f with values in gamma space.
  If rendering in gamma color space, multiply them component-wise against
  the final calculated color after rendering.
  If rendering in linear space, first convert the values to linear space by
  rising to the power 2.2, then multiply component-wise against the final
  calculated color after rendering.
****

The purpose of pname:colorCorrection is to make a scene appear natural and
blend with the real world.

include::{generated}/validity/structs/XrAmbientLightANDROID.adoc[]
--

[open,refpage='XrSphericalHarmonicsANDROID',type='structs',desc='Contains information about light estimation',xrefs='xrGetLightEstimateANDROID XrAmbientLightANDROID XrDirectionalLightANDROID']
--
The slink:XrSphericalHarmonicsANDROID structure contains spherical harmonics
representing the lighting of the scene.

include::{generated}/api/structs/XrSphericalHarmonicsANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  Valid structures include slink:XrAmbientLightANDROID and
  slink:XrDirectionalLightANDROID.
* pname:state is the elink:XrLightEstimateStateANDROID representing the
  state of the light estimate.
* pname:kind is the elink:XrSphericalHarmonicsKindANDROID requested by the
  application.
* pname:coefficients is a two-dimensional code:float array with dimensions 9
  rows and 3 columns.
  The 3 columns corresponding to color channels red, green and blue
  respectively.
  Each channel has 9 spherical harmonic coefficients.
****

The pname:coefficients are to be used in a special function which takes a
direction as an input and outputs the light color coming from that
direction.
More detail available in R. Ramamoorthi and P. Hanrahan,
link:http://graphics.stanford.edu/papers/envmap/envmap.pdf["An efficient
representation for irradiance environment maps,"] in _SIGGRAPH '01:
Proceedings of the 28th annual conference on Computer graphics and
interactive techniques_, ACM, Aug.
2001, pp.
497-500.
link:https://doi.org/10.1145/383259.383317[doi:10.1145/383259.383317].


include::{generated}/validity/structs/XrSphericalHarmonicsANDROID.adoc[]
--

[open,refpage='XrSphericalHarmonicsKindANDROID',type='enums',desc='The kind of spherical harmonics requested by the application',xrefs='XrSphericalHarmonicsANDROID']
--
The elink:XrSphericalHarmonicsKindANDROID enumeration identifies to the
runtime, what type of spherical harmonics the application is requesting.

include::{generated}/api/enums/XrSphericalHarmonicsKindANDROID.adoc[]

The enumeration values have the following meanings:

include::{generated}/api/enums/XrSphericalHarmonicsKindANDROID.comments.adoc[]
--

[open,refpage='XrDirectionalLightANDROID',type='structs',desc='Contains information about light estimation',xrefs='xrGetLightEstimateANDROID XrAmbientLightANDROID XrSphericalHarmonicsANDROID']
--
The slink:XrDirectionalLightANDROID structure contains light estimation
data.

include::{generated}/api/structs/XrDirectionalLightANDROID.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
  Valid structures include slink:XrAmbientLightANDROID,
  slink:XrSphericalHarmonicsANDROID, and slink:XrDirectionalLightANDROID.
* pname:state is the elink:XrLightEstimateStateANDROID representing the
  state of the light estimate.
* pname:intensity is an slink:XrVector3f representing the intensity of the
  directional light.
  Each component of the vector corresponds to the red, green, and blue
  channels.
* pname:direction is an slink:XrVector3f representing the light direction.
****

include::{generated}/validity/structs/XrDirectionalLightANDROID.adoc[]
--

[open,refpage='XrLightEstimateStateANDROID',type='enums',desc='The state of the light estimate returned by the runtime',xrefs='XrLightEstimateANDROID']
--
The elink:XrLightEstimateStateANDROID enumeration indicates the state of the
light estimate returned by the runtime.

include::{generated}/api/enums/XrLightEstimateStateANDROID.adoc[]

The enumeration values have the following meanings:

include::{generated}/api/enums/XrLightEstimateStateANDROID.comments.adoc[]
--

==== Example code for light estimation

The following example code demonstrates how to get all possible light
estimation quantities from the runtime

[source,cpp]
----
XrSession session;  // Created at app startup
XrSpace appSpace;   // Created previously.
PFN_xrCreateLightEstimatorANDROID xrCreateLightEstimatorANDROID; // Created previously.
PFN_xrDestroyLightEstimatorANDROID xrDestroyLightEstimatorANDROID; // Created previously.
PFN_xrGetLightEstimateANDROID xrGetLightEstimateANDROID; // Created previously.

XrLightEstimatorANDROID estimator;
XrLightEstimatorCreateInfoANDROID createInfo = {
    .type = XR_TYPE_LIGHT_ESTIMATOR_CREATE_INFO_ANDROID};
CHK_XR(xrCreateLightEstimatorANDROID(session, &createInfo, &estimator));

// Every frame
XrTime updateTime;  // Time used for the current frame's simulation update.

XrLightEstimateGetInfoANDROID info = {
    .type = XR_TYPE_LIGHT_ESTIMATE_GET_INFO_ANDROID,
    .space = appSpace,
    .time = updateTime,
};

XrDirectionalLightANDROID directionalLight = {
    .type = XR_TYPE_DIRECTIONAL_LIGHT_ANDROID,
};

XrSphericalHarmonicsANDROID sphericalHarmonics = {
    .type = XR_TYPE_SPHERICAL_HARMONICS_ANDROID,
    .next = &directionalLight,
};

// Querying both TOTAL or AMBIENT spherical harmonics in one call will result in an error because chaining two structs with the same type is not allowed
bool useTotalSH; // initialized previously
if (useTotalSH) {
  sphericalHarmonics.kind = XR_SPHERICAL_HARMONICS_KIND_TOTAL_ANDROID;
} else {
  sphericalHarmonics.kind = XR_SPHERICAL_HARMONICS_KIND_AMBIENT_ANDROID;
}

XrAmbientLightANDROID ambientLight = {
    .type = XR_TYPE_AMBIENT_LIGHT_ANDROID,
    .next = &sphericalHarmonics,
};

XrLightEstimateANDROID estimate = {
    .type = XR_TYPE_LIGHT_ESTIMATE_ANDROID,
    .next = &ambientLight,
};

XrResult result = xrGetLightEstimateANDROID(estimator, &info, &estimate);
if (result == XR_SUCCESS &&
    estimate.state == XR_LIGHT_ESTIMATE_STATE_VALID_ANDROID) {
  // use directionalLight, totalSh, ambientSh, ambientLight if each
  // struct has a valid state field
}

// When you want to disable light estimation
CHK_XR(xrDestroyLightEstimatorANDROID(estimator));

----

include::{generated}/interfaces/XR_ANDROID_light_estimation.adoc[leveloffset=1]

==== Issues

==== Version History

* Revision 1, 2024-09-16 (Cairn Overturf)
** Initial extension description
