// Copyright (c) Ultraleap Limited. All rights reserved.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/XR_ULTRALEAP_hand_tracking_forearm.adoc[]


*Last Modified Date*::
    2022-04-19

*IP Status*::
    No known IP claims.

*Contributors*::
    Robert Blenkinsopp, Ultraleap +
    Adam Harwood, Ultraleap +

*Overview*

This extension augments the apiext:XR_EXT_hand_tracking extension to enable
applications to request the default set of 26 hand joints, with the addition
of a joint representing the user's elbow.

The application must: also enable the apiext:XR_EXT_hand_tracking extension
in order to use this extension.

*New joint set*

This extension extends the elink:XrHandJointSetEXT enumeration with a new
member ename:XR_HAND_JOINT_SET_HAND_WITH_FOREARM_ULTRALEAP.
This joint set is the same as the ename:XR_HAND_JOINT_SET_DEFAULT_EXT, plus
a joint representing the user's elbow,
ename:XR_HAND_FOREARM_JOINT_ELBOW_ULTRALEAP.

[open,refpage='XrHandForearmJointULTRALEAP',type='enums',desc='The name of hand joints that can be tracked including the elbow',xrefs='XrHandJointEXT']
--
include::{generated}/api/enums/XrHandForearmJointULTRALEAP.txt[]

[NOTE]
.Note
====
The first dlink:XR_HAND_JOINT_COUNT_EXT members of
elink:XrHandForearmJointULTRALEAP are identical to the members of
elink:XrHandJointEXT and can: be used interchangeably.
====
--

The ename:XR_HAND_FOREARM_JOINT_ELBOW_ULTRALEAP joint represents the center
of an elbow and is orientated with the backwards (+Z) direction parallel to
the forearm and points away from the hand.

The up (+Y) direction is pointing out of the dorsal side of the forearm.
The X direction is perpendicular to Y and Z and follows the right hand rule.

[open,refpage='XR_HAND_FOREARM_JOINT_COUNT_ULTRALEAP',type='defines',desc='The number of hand joint enums defined in XrHandForearmJointULTRALEAP',xrefs='XrHandForearmJointULTRALEAP']
--
include::{generated}/api/defines/XR_HAND_FOREARM_JOINT_COUNT_ULTRALEAP.txt[]

dlink:XR_HAND_FOREARM_JOINT_COUNT_ULTRALEAP defines the number of hand joint
enumerants defined in elink:XrHandForearmJointULTRALEAP.
--

*New Object Types*

*New Flag Types*

*New Enum Constants*

* dlink:XR_HAND_FOREARM_JOINT_COUNT_ULTRALEAP

elink:XrHandJointSetEXT enumeration is extended with:

* ename:XR_HAND_JOINT_SET_HAND_WITH_FOREARM_ULTRALEAP

*New Enums*

* elink:XrHandForearmJointULTRALEAP

*New Structures*

*New Functions*

*Issues*

*Version History*

* Revision 1, 2022-04-19 (Robert Blenkinsopp)
** Initial version

