// Copyright (c) 2024 ByteDance
//
// SPDX-License-Identifier: CC-BY-4.0
include::{generated}/meta/XR_BD_dynamic_object_keyboard.adoc[]

*Last Modified Date*::
    2025-08-05

*IP Status*::
    No known IP claims.

*Contributors*::
    Zijian Wang, ByteDance +
    Zhipeng Liu, ByteDance +
    Shuai Liu, ByteDance +

==== Overview

The apiext:XR_BD_dynamic_object_keyboard extension enables the keyboard to
be tracked as a type of dynamic object by the
apiext:XR_BD_dynamic_object_tracking extension.

==== Inspect System Capability

[open,refpage='XrSystemDynamicObjectKeyboardPropertiesBD',type='structs',desc='System property for dynamic object keyboard.',xrefs='XrSystemProperties xrGetSystemProperties']
--
The slink:XrSystemDynamicObjectKeyboardPropertiesBD structure is defined as:

include::{generated}/api/structs/XrSystemDynamicObjectKeyboardPropertiesBD.adoc[]

.Member Descriptions
****
* pname:type is the elink:XrStructureType of this structure.
* pname:next is code:NULL or a pointer to the next structure in a structure
  chain.
* pname:supportsDynamicObjectKeyboard is an basetype:XrBool32, with
  ename:XR_TRUE indicating that the system supports tracking keyboard, and
  ename:XR_FALSE indicating that the system does not support tracking
  keyboard.
****

An application can: inspect whether the system is capable of tracking
keyboards by chaining an slink:XrSystemDynamicObjectKeyboardPropertiesBD
structure to the slink:XrSystemProperties::pname:next chain when calling
flink:xrGetSystemProperties.

If slink:XrSystemSpatialSensingPropertiesBD::pname:supportsSpatialSensing is
ename:XR_FALSE or
slink:XrSystemDynamicObjectTrackingPropertiesBD::pname:supportsDynamicObjectTracking
is ename:XR_FALSE, then pname:supportsDynamicObjectKeyboard must: also be
ename:XR_FALSE.

If a runtime returns ename:XR_TRUE for pname:supportsDynamicObjectKeyboard,
the system supports dynamic keyboard tracking.
This implies that
slink:XrSystemDynamicObjectTrackingPropertiesBD::pname:supportsDynamicObjectTracking
and slink:XrSystemSpatialSensingPropertiesBD::pname:supportsSpatialSensing
must: also be ename:XR_TRUE.

Note that pname:supportsDynamicObjectKeyboard may: be ename:XR_TRUE, even if
the application has not obtained the permission required by the system.

Evaluation of permissions takes place later, in the asynchronous operation
started by flink:xrStartSenseDataProviderAsyncBD.

include::{generated}/validity/structs/XrSystemDynamicObjectKeyboardPropertiesBD.adoc[]
--

==== The Keyboard Dynamic Object

Applications can: obtain component data through
flink:xrGetSpatialEntityComponentDataBD from the spatial entity of a
keyboard, such as location, semantic label, or bounding box.

Applications can: also create an slink:XrSpace for the spatial entity of a
keyboard and obtain the location through flink:xrLocateSpace or
flink:xrLocateSpaces.

See more details in <<bd_dynamic_object_tracking-locate-dynamic-object>>.

The origin of the keyboard space is located at the geometric center point
inside the bounding box, and the positive Z axis extends outward normal to
the typing face, and the X-Y plane of the keyboard matches the intended
viewing orientation when typing.
On a QWERTY keyboard, the positive Y direction extends from the center of
the keyboard to the row of number keys, and the positive X direction extends
from the center of the keyboard toward the side with the return or enter
key.

include::{generated}/interfaces/XR_BD_dynamic_object_keyboard.adoc[leveloffset=1]


==== Issues

==== Version History

* Revision 1, 2025-08-05 (Zijian Wang)

** Initial extension description
